### ISSUE TITLE
rnpkeys does not display possibility of exporting private keys in the help text

### ISSUE THREAD

**Issue by antonsviridenko** [rnpgp/rnp#1024]
While this feature is already implemented in https://github.com/rnpgp/rnp/pull/652 and works as
expected, i.e. `rnpkeys --export-key --secret 94352b599eefa567` 
help text does not list the "secret" option:

```
rnp 0.9.0+git20200105.612.0e311c7
All bug reports, praise and chocolate, please, to:
Ribose Inc. <packaging@ribose.com>
Usage: rnpkeys --help OR
        --export-key [options] OR
        --generate-key [options] OR
        --import-key [options] OR
        --list-keys [options] OR
        --version
where options are:
        [--cipher=<cipher name>] AND/OR
        [--coredumps] AND/OR
        [--expert] AND/OR
        [--with-sigs] AND/OR
        [--force] AND/OR
        [--hash=<hash alg>] AND/OR
        [--homedir=<homedir>] AND/OR
        [--keyring=<keyring>] AND/OR
        [--output=file] file OR
        [--keystore-format=<format>] AND/OR
        [--userid=<userid>] AND/OR
        [--verbose]
```

## Expected Behavior

"secret" option must be listed in available options

## Actual Behavior

"secret" is not mentioned

**Comment by antonsviridenko** [comment]
The man page for "rnpkeys" https://github.com/rnpgp/rnp/blob/master/src/rnpkeys/rnpkeys.1 also does not contain information about the "secret" option.

**Comment by ni4** [comment]
@antonsviridenko yeah, man and help messages are a bit outdated.
Related to #506
