### ISSUE TITLE
rnpkeys --export --userid uid doesn't work.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1057]
## Description

Due to incorrect code in `rnpkeys.cpp` CLI  doesn't respect `--userid` argument:
```
    case CMD_EXPORT_KEY: {
        key = f;
        if (!key) {
            list *ids = NULL;
            if ((ids = rnp_cfg_getlist(cfg, CFG_USERID)) && list_length(*ids) > 0) {
                f = (fs = rnp_cfg_getlist_string(cfg, CFG_USERID, 0)).c_str();
            }
        }
        if (!key) {
            (void) fprintf(stderr, "key '%s' not found\n", f);
            return 0;
        }
        return cli_rnp_export_keys(cfg, rnp, key);
    }
```

Should be fixed, including the CLI test which checks this case.

**Comment by ni4** [comment]
...additionally, `fprintf(stderr, "key '%s' not found\n", f)` doesn't make sense here since will always print null.

**Comment by antonsviridenko** [comment]
@ni4 looks like it is already fixed, at least the mentioned code was changed by you since then...

**Comment by ni4** [comment]
@antonsviridenko Yeah, it appears to be fixed via refactoring commit, tests were updates as well. Let's close it now.
