### ISSUE TITLE
Improve input type detection during signature/key import.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1065]
## Description

When rnp checks imported contents, it relies on PUBLIC KEY/SIGNATURE armor header.
However, GnuPG uses PUBLIC KEY header for exported key revocation, causing the importing error when `rnpkeys --import revcert.asc` command is issued.

**Comment by rrrooommmaaa** [comment]
Do we have a sample `revcert.asc` file in `tests/data'?

**Comment by ni4** [comment]
@rrrooommmaaa There is revocation signature available at `data/test_key_validity/alice-rev.pgp`, just make sure to enarmor it with correct (public key) headers.

**Comment by ni4** [comment]
Fixed via https://github.com/rnpgp/rnp/pull/1309
