### ISSUE TITLE
Annoying linker warning: stream-common.cpp:(.text+0x2666): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

### ISSUE THREAD

**Issue by jpo234** [rnpgp/rnp#1071]
## Description

The function init_tmpfile_dest in src/librepgp/stream-common.cpp calls the deprecated mktemp function. That causes an annoying linker warning.
This is what the [man-page](https://linux.die.net/man/3/mktemp) has to say:

> Never use mktemp(). Some implementations follow 4.3BSD and replace XXXXXX by the current process ID and a single letter, so that at most 26 different names can be returned. Since on the one hand the names are easy to guess, and on the other hand there is a race between testing whether the name exists and opening the file, every use of mktemp() is a security risk. The race is avoided by mkstemp(3). 

## Steps to Reproduce

1. Link against a static librnp-0.a

## Expected Behavior

No warning

## Actual Behavior

A Warning:
```
rnpgp/lib/librnp-0.a(stream-common.cpp.o): In function `init_tmpfile_dest(pgp_dest_t*, char const*, bool)':
stream-common.cpp:(.text+0x2666): warning: the use of `mktemp' is dangerous, better use `mkstemp' or `mkdtemp'

```

[This is the offending line](https://github.com/rnpgp/rnp/blob/5a39e2b1955c97c032a7b63df272397d935b40cd/src/librepgp/stream-common.cpp#L904).

**Comment by ni4** [comment]
@jpo234 Thanks for reporting. Will need some time to get to it (and to make it compatible with Windows).

**Comment by ni4** [comment]
PR #1127 may be useful.
