### ISSUE TITLE
kr-def-key parameter ignored

### ISSUE THREAD

**Issue by rrrooommmaaa** [rnpgp/rnp#1075]
## Description

I would expect to sign (or do some other operation) with default key if the key is not specified for the operation. However, `kr-def-key` configuration value never gets to `cli_rnp_t.defkey` field.

## Steps to Reproduce
???

## Expected Behavior
Value from `CFG_KR_DEF_KEY` should go to `cli_rnp_t.defkey`

## Actual Behavior
Value from `CFG_KR_DEF_KEY` is never used.
Always trying to use the first key in the keystore.

**Comment by ni4** [comment]
@rrrooommmaaa actually kr-def-key is not a command line parameter, but some internal variable which is set based on keyring configuration. In most cases it would pick up the first key in the keyring, however may also parse GnuPG config via `conffile()` function.

**Comment by rrrooommmaaa** [comment]
@ni4 Anyway, it is set in `rnp_cfg_set_defkey` and never read afterwards. Where is it supposed to be read?

**Comment by ni4** [comment]
@rrrooommmaaa Okay, now it's an issue :) Probably it was lost somewher during CLI->FFI transition.

**Comment by rrrooommmaaa** [comment]
@ni4 I have re-worded the issue.

**Comment by ni4** [comment]
@rrrooommmaaa Did you start working on this issue? I plan to introduce some changes which may have impact on it (make `rnp_cfg_t` field of  `rnp_cli_t` structure, so we'll not pass two structures as parameters). Then it would be logical to replace rnp->defkey with `rnp_cfg_getstr(rnp_cli_get_cfg(rnp), CFG_KR_DEF_KEY))`.

**Comment by rrrooommmaaa** [comment]
I haven't yet. Feel free to re-assign.

**Comment by ni4** [comment]
Ok, thanks!
