### ISSUE TITLE
CFG_KEYSTORE_DISABLED int or bool?

### ISSUE THREAD

**Issue by rrrooommmaaa** [rnpgp/rnp#1082]
## Description

In some calls `rnp_cfg_setbool()` is used, in others -- `rnp_cfg_setint()` for `CFG_KEYSTORE_DISABLED` configuration setting

## Expected Behavior

I would expect to have either `bool` or `int` throughout the app.

**Comment by dewyatt** [comment]
This is generally by design and you'll see the code in `rnpcfg.cpp` should handle it correctly based on the underlying type. However, I agree it's inconsistent and we should just use `bool`.
