### ISSUE TITLE
RNP and GPG report different key expiration times

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1089]
## Description

For a key that was extended, RNP reports that the key has expired at an earlier time - not at the most recent expiration time.

## Steps to Reproduce

1. Import key 698e2885c1de74e32cd503ad295c746984af7f0c with rnpkeys
2. rnp --list 698e2885c1de74e32cd503ad295c746984af7f0c |grep EXPIRED

## Expected Behavior

GPG reports expiration date: 2020-03-17

## Actual Behavior

RNP reports expiration date 2018-04-12

**Comment by kaie** [comment]
I made the key available at
https://kuix.de/misc/698E2885C1DE74E32CD503AD295C746984AF7F0C.asc

**Comment by ni4** [comment]
@kaie thanks for the report. This happens because of the yet incorrect key expiration check - it just saves key expiration specified in the latest signature. I'm going to fix this together with other changes very soon.
