### ISSUE TITLE
Prune spurious 'keyring not found' output shown on every single command

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#11]
Almost every command with `netpgp` shows up with this output preceding any action (if there is no `${HOME}/.gnupg`):

``` sh
${HOME}/.gnupg/pubring.gpg: No such file or directory
Can't read pubring /root/.gnupg/pubring.gpg
Can't read pub keyring
can't initialise
```

This should show useful output instead.

**Comment by ronaldtse** [comment]
@ni4 @dewyatt Is this still valid? Thanks!

**Comment by ni4** [comment]
Yeah, now it has a bit different text and behavior but still needs fixing.
