### ISSUE TITLE
very slow listing of big (poisoned?) key

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1101]
Download this key, which is a version of Werner Koch's key, but it might be a poisoned version. It has 3 user IDs, and each has around 1600 signatures:
https://kuix.de/misc/wk-full.asc

When listing the key with rnpkeys --list --with-sigs it is very very slow, while gpg lists it in less than 2 seconds.

```
mkdir /tmp/r2
rnpkeys --homedir=/tmp/r2 --import ~/Download/wk-full.asc
```

Speed of normal listing is acceptable, although it takes a couple of seconds:
```
rnpkeys --homedir=/tmp/r2 --list
```

Speed of listing with sigs isn't acceptable, it seems to get slower as it proceeds. Maybe you have some code that always needs to start iterating from the beginning, instead of proceeding from an offset?
```
rnpkeys --homedir=/tmp/r2 --list --with-sigs
```

**Comment by ni4** [comment]
Hi @kaie. Thanks for reporting, I'll take a look. Most likely it's because some O(n^2) weak places during signature list processing. I'll take a look, it must be definitely optimized till the release.

**Comment by ni4** [comment]
@kaie PR #1109 fixes time to 1-3 seconds on both cases on my development machine.
Still need some time to check and settle things down.
