### ISSUE TITLE
Key validity extension signature is ignored/rejected, if done after expiration

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1115]
We have an example key, that RNP treats as "expired".
GnuPG treats it as "never expires".

The key contains a self-signature, which defines an expiration date.
There's is an additional self-signature, made at a later time, which does not define an expiration.

I assume that GnuPG accepts the second signature, overriding the original expiration.

The second signature was made after the original expiration date.
When RNP processes the key, a log message is printed:

[signature_check() /home/user/moz/commcent/mozilla/comm/third_party/rnp/src/librepgp/stream-sig.cpp:1155] signature made after key expiration

I'm guessing that RNP decides to ignore the 2nd signature.

Searching the web, it appears that the common opinion is that extending a key after it expired is permitted.

Suggestion: Please allow self-signatures that are made after the key's expiration date.

I have been given an example key, which I can share in private, only, because the key owner prefers to have their user IDs be kept confidential.

**Comment by kaie** [comment]
I have to say, I haven't yet checked this with the tip of RNP. Let me do that first.

**Comment by ni4** [comment]
@kaie Thanks for reporting. It's logical trick - in current code (at master, not latest release) we search for latest self-signature with key expiration subpacket, missing the point where latest signature may be without it, marking key as non-expiring. So no need to share key - I think i'll be able to reproduce this issue, and fix it.

**Comment by kaie** [comment]
Thanks, this is now working with the test key I was using.
