### ISSUE TITLE
ci: Build with clang-cl

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#1129]
## Description

I couldn't find any open issue for this and since the Thunderbird guys are building with clang-cl, we should probably add this to CI.

(I'm planning to tackle this myself, but if anyone is already working on this let me know!)

**Comment by ni4** [comment]
@dewyatt #997 could be related (maybe not well formulated though). We definitely need an ability to make a native Windows build without MinGW/MSYS.

**Comment by ni4** [comment]
@dewyatt What do you think about including this into v0.14 milestone? Since this is not urgent for TB since they have their own build scripts, but still would be nice to have in the release.

**Comment by dewyatt** [comment]
> @dewyatt What do you think about including this into v0.14 milestone? Since this is not urgent for TB since they have their own build scripts, but still would be nice to have in the release.

This issue is mostly focused on CI so not related to a release per se. I don't see it as high priority but I don't see it as low priority either. If we're constantly breaking the build for the TB people because we don't have any similar build in CI, that's going to create some unnecessary friction.

**Comment by ronaldtse** [comment]
I think it would be best to have the clang-cl build as soon as we can, because that would prevent us from being the source of errors to TB...

**Comment by ronaldtse** [comment]
@dewyatt are you handling this? Or should we seek extra help? Thanks!

**Comment by dewyatt** [comment]
> @dewyatt are you handling this? Or should we seek extra help? Thanks!

I looked at it briefly and observed that adding `-T ClangCL` leads to duplicate symbol errors. I came up with a quick workaround but it breaks all other CI.

I'd rather continue on py-rnp if someone else wants to do a proper fix here...

**Comment by dewyatt** [comment]
(Unassigning but I can come back if we have trouble finding someone)

**Comment by ronaldtse** [comment]
Thanks for updating this, @antonsviridenko @rrrooommmaaa would you have time to make this work?

**Comment by ronaldtse** [comment]
@maxirmx would you have time to handle this? Thanks.

**Comment by maxirmx** [comment]
@ronaldtse 
Yes, I can handle it.  No sure though what operating systems to support. Ubuntu ?

**Comment by ronaldtse** [comment]
@maxirmx We will want to handle the platforms that Thunderbird builds RNP on. Do we have a list of those platforms somewhere?

**Comment by maxirmx** [comment]
Clang issues are only indirectly related to rnp.
The first one:

**Target:**  CentOS 8
**Tests**   (normal, 2.3.1, clang, clang++)
**Module:**  libgcrypt / 1.9.3
**Error:**
```
basic.c:315:16: error: inline assembly requires more registers than available
  asm volatile("movdqu %[data0], %%xmm0\n"
               ^
basic.c:315:16: error: inline assembly requires more registers than available
```


Other tests use  libgcrypt /v1.8.7  and  libgcrypt / v1.9.0-beta277  which are compiled without issues.

**Comment by maxirmx** [comment]
**Target:** CentOS 8
**Tests** (normal, beta, clang, clang++)
**Module:** GnuPG v2.3.0-beta983
**Error:**
```
libcommon.a(libcommon_a-iobuf.o):(.bss+0x8): multiple definition of `iobuf_debug_mode'
t-iobuf.o:(.bss+0x0): first defined here
``` 
Other tests use GnuPG v2.2.24 whicj compiles without issues.

**Comment by maxirmx** [comment]
Target: CentOS 7
Tests pkgconfig-cmake-target (no, clang, clang++), pkgconfig-cmake-target (yes, clang, clang++
Module: librepgp

```
In file included from /__w/rnp/rnp/src/librepgp/stream-common.cpp:50:
In file included from /__w/rnp/rnp/src/lib/crypto/mem.h:34:
In file included from /usr/include/botan-2/botan/secmem.h:12:
/usr/include/botan-2/botan/mem_ops.h:147:18: error: no member named 'is_trivially_copyable' in namespace 'std'
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(T), "");
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-2/botan/mem_ops.h:124:45: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
                                       ~~~~~^
/usr/include/botan-2/botan/mem_ops.h:147:46: error: 'T' does not refer to a value
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(T), "");
                                             ^
/usr/include/botan-2/botan/mem_ops.h:124:67: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
                                                                  ^
/usr/include/botan-2/botan/mem_ops.h:145:19: note: declared here
template<typename T> inline void typecast_copy(uint8_t out[], T in[], size_t N)
                  ^
/usr/include/botan-2/botan/mem_ops.h:147:18: error: no member named 'value' in the global namespace
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(T), "");
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-2/botan/mem_ops.h:124:71: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
                                                                    ~~^
/usr/include/botan-2/botan/mem_ops.h:170:18: error: no member named 'is_trivially_copyable' in namespace 'std'
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(From) && std::is_trivial<To>::value, "");
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-2/botan/mem_ops.h:124:45: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
                                       ~~~~~^
/usr/include/botan-2/botan/mem_ops.h:170:46: error: 'From' does not refer to a value
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(From) && std::is_trivial<To>::value, "");
                                             ^
/usr/include/botan-2/botan/mem_ops.h:124:67: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
                                                                  ^
/usr/include/botan-2/botan/mem_ops.h:168:27: note: declared here
template <class To, class From> inline To typecast_copy(const From *src) noexcept
                          ^
/usr/include/botan-2/botan/mem_ops.h:170:18: error: no member named 'value' in the global namespace
   static_assert(BOTAN_IS_TRIVIALLY_COPYABLE(From) && std::is_trivial<To>::value, "");
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/botan-2/botan/mem_ops.h:124:71: note: expanded from macro 'BOTAN_IS_TRIVIALLY_COPYABLE'
#define BOTAN_IS_TRIVIALLY_COPYABLE(T) std::is_trivially_copyable<T>::value
```
