### ISSUE TITLE
Improve performance of loading/exporting of huge keyrings.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1133]
## Description

As it was reported via email, loading/exporting of large amount of keys may take a significant time. 
This most likely is linked to usage of list type, and should be fixed up by using std::vector instead.

**Comment by ni4** [comment]
@pbrunschwig Could you please check whether this fixed slowdowns you had?

**Comment by pbrunschwig** [comment]
Performance is much better now

**Comment by ni4** [comment]
@pbrunschwig Thanks for confirming this!
