### ISSUE TITLE
decrypt failure with error: wrong mpi bit count, failed to get rsa m

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1143]
I regularly receive encrypted email from a bug tracking system.

Today I received a message that RNP cannot decrypt, it reports:
```
[get_packet_body_mpi() /home/user/github/rnp/src/librepgp/stream-packet.cpp:518] wrong mpi bit count
[stream_parse_pk_sesskey() /home/user/github/rnp/src/librepgp/stream-packet.cpp:1132] failed to get rsa m
```

Secret key is available. I compared with another encrypted email from the same source, same key was used.

GnuPG is able to decrypt the message correctly.

I'm attaching the message.

**Comment by kaie** [comment]
[wrong-mpi-bit-count.txt](https://github.com/rnpgp/rnp/files/4644657/wrong-mpi-bit-count.txt)

**Comment by kaie** [comment]
Is this encrypted message sufficient to analyze the problem? I cannot share the secret key.

**Comment by ni4** [comment]
@kaie It seems enough, however will need some time/efforts to analyze what's the best behavior in this case. In this file encrypted RSA M parameter is claimed to be 4089-bits long, however actual MPI is 4088-bits long (high-order byte is zero). RFC 4880 claims it as ill-formed (however, doesn't seem to have any rule on handling these as no-good).
Do you know whether this message issued by GnuPG, or some other implementation?

**Comment by kaie** [comment]
The message was sent by bugzilla.mozilla.org and thanks to justdave who looked up what software is used behind the scenes: Crypt::OpenPGP and Crypt::SMIME modules in Perl - https://github.com/mozilla-bteam/bmo/blob/master/extensions/SecureMail/Extension.pm

**Comment by kaie** [comment]
it was sent by the server on bugzilla.mozilla.org - according to dkl : it "uses a compiled cli command made from https://www.npmjs.com/package/openpgp" - https://github.com/mozilla-bteam/tocotrienol

**Comment by kaie** [comment]
... which is a front end to OpenPGP.js

**Comment by ni4** [comment]
> Sorry, apparently this no longer applies to the current version

Do you mean the RNP or OpenPGP.js?
Anyway, I issued the PR #1144 which should fix this - since GnuPG supports decryption of such messages, and since message may be easily edited to be then decrypted by RNP, we should support such case with buggy implementations.
