### ISSUE TITLE
Drop utils.h include in rnp.h

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#1151]
## Description

Since https://github.com/rnpgp/rnp/pull/962 we have this in `rnp.h`:
```c
#if defined(__cplusplus)
}

#include "utils.h"

#endif
```

This breaks (or has unintended consequences, depending on whether a `utils.h` exists) C++ API clients.

**Comment by dewyatt** [comment]
I'm going to end up doing this as part of https://github.com/rnpgp/rnp/issues/1135

**Comment by ni4** [comment]
Closing as it was fixed in #1173
