### ISSUE TITLE
Double key export via CLI

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1153]
## Description

In some cases rnpkeys exports double key via `--export` command.
At first glance it doesn't happen without subkeys, and happens if there is at least one subkey.

## Steps to reproduce
```
mkdir .rnp
rnpkeys --homedir .rnp --import src/tests/data/test_key_validity/alice-sub-sec.pgp
rnpkeys --homedir .rnp --export Alice > alice.asc
rnp --list-packets alice.asc
```

**Comment by antonsviridenko** [comment]
I can take this one

**Comment by ni4** [comment]
@antonsviridenko You are welcome. Also you may be interested in #1160 .
