### ISSUE TITLE
Cannot import key with "Unknown pk algorithm : 3"

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1154]
The following keys cannot be imported with error message "Unknown pk algorithm : 3"

This key:
http://keyserver.ubuntu.com/pks/lookup?search=0x864E1BDC5434509D&fingerprint=on&op=index
uses:
    public key algorithm: 3 (RSA (Sign-Only))

And this key:
http://keyserver.ubuntu.com/pks/lookup?search=0x1D02458D6890F8381B37471610720B1536BF3AED&fingerprint=on&op=index
contains a signature by the first key.

Should these get accepted?

RSA Sign-Only appears to have been valid in the past, but is now deprecated.

**Comment by kaie** [comment]
tracked by https://bugzilla.mozilla.org/show_bug.cgi?id=1641265

**Comment by ni4** [comment]
@kaie I also got over this recently. We definitely should support such keys/sigs, at least for load/verification, not signature/key generation. Will fix this soon.

**Comment by ni4** [comment]
@kaie As of current master branch this issue must be fixed.

**Comment by kaie** [comment]
Thanks. I can import the first key.
The second key can be imported, too, but apparently, only partially. Looking at the imported key, no subkey is shown (only primary). Do you want to track that in a separate issue, or in here?

**Comment by ni4** [comment]
@kaie Sorry, I missed links to the keys in the first message. Let me first check those out...

**Comment by ni4** [comment]
@kaie The problem there is too large ElGamal subkey size (it is 4096, while due to unknown reasons we were stick to 3076 as maximum). Will create a new issue and provide a fix.
