### ISSUE TITLE
Add rnpkeys --permissive command for key import.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1160]
## Description

As of PR #1159 we support 'permissive' key import in FFI, when only bad keys/signatures are skipped.
This feature should be added to the CLI as well.

**Comment by antonsviridenko** [comment]
I think it should be an option, not a command, right? Should it apply only to keys import, not signatures?

**Comment by ni4** [comment]
@antonsviridenko Yeah, it should be an option, not a command. Mistype due to quick-typing. Currently it can be set only for the key import, no way to set the corresponding flag for the signature import.
