### ISSUE TITLE
crash reports

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1171]
We should discuss how to best submit crash reports to you.

Thunderbird is using an automated crash reporting system, and details of crashes can be seen on the crash-stats server.

Wayne told me about two crashes that occurred with RNP. They were with a TB 78 beta build with build date 2020-06-11 - that was still using an RNP snapshot from 2020-05-30.

Here are the links to the two crashes, which include information about the stack:
https://crash-stats.mozilla.org/report/index/79add039-c2c4-4b5f-99af-03a4c0200615
https://crash-stats.mozilla.org/report/index/4355857e-94f1-4453-9e74-a72e00200615

Does someone of you have an account at bugzilla.mozilla.org, or wants to create one?
It might be useful to be able to CC you on bug reports, in particular for security sensitive bugs, should we run into some.

But if you prefer to avoid bugzilla and prefer to use github, only, we can.

**Comment by ni4** [comment]
@kaie Thanks for the reports, will take a look. At first glance those crashes looks a bit strange.

I think we still would need to create at least issues with links to bugzilla here, to keep track of closed issues/progress. But anyway I created account at Bugzilla: https://bugzilla.mozilla.org/user_profile?user_id=665047
Feel free to CC to it on rnp-related issues.
