### ISSUE TITLE
/usr/bin/ld: cannot find -lval-NOTFOUND

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1196]
When building the snapshot from 2020-07-06 locally on Linux, I get this error:
```
Scanning dependencies of target encrypt
[ 64%] Building C object src/examples/CMakeFiles/encrypt.dir/encrypt.c.o
[ 65%] Linking C executable encrypt
/usr/bin/ld: cannot find -lval-NOTFOUND
collect2: error: ld returned 1 exit status
make[2]: *** [src/examples/CMakeFiles/encrypt.dir/build.make:85: src/examples/encrypt] Error 1
make[1]: *** [CMakeFiles/Makefile2:101: src/examples/CMakeFiles/encrypt.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```

cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr/local/botan-rnp-shared -DBUILD_SHARED_LIBS=on -DBUILD_TESTING=off ../rnp

**Comment by dewyatt** [comment]
What distribution+version and what version of cmake?

**Comment by kaie** [comment]
debian 10 on qubes

cmake version 3.13.4

**Comment by dewyatt** [comment]
Confirmed build issue, taking a look

**Comment by dewyatt** [comment]
Ok I should have a fix for this shortly

**Comment by kaie** [comment]
Ok, thanks for the hint. cmake version 3.16.3 was available in the debian buster backports repository. That works for me.
