### ISSUE TITLE
Update Fuzzer section of `develop.adoc` due to #1195

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1199]
From @ni4 :

> LGTM, except minor copyright year mismatch.
> And it would be also good to update Fuzzer section of develop.adoc once this is merged.

**Comment by tomrittervg** [comment]
I think we should change -DENABLE_FUZZING to -DENABLE_FUZZERS also.

**Comment by ni4** [comment]
Closing as it was fixed in #1216
