### ISSUE TITLE
Provide new API to obtain the revocation date or revocation signature

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1200]
I need the ability to obtain the date on which a key was revoked.

I can think of two alternatives, either a specific new API rnp_key_get_revocation_reason that returns a timestamp.

Alternatively, a more general API that uses rnp_key_get_signature_at, and then a new function that returns the signature type, like rnp_signature_get_type(rnp_signature_handle_t), then the application code loop the signatures, find the revocation signature, and obtain its timestamp using rnp_signature_get_creation.

**Comment by ni4** [comment]
@kaie Probably, the easiest way would be to add function `rnp_key_get_revocation_signature()`, to be safer in case of multiple revocation signatures/fake ones/whatever else, leaving the revocation detection logic to this library.

**Comment by kaie** [comment]
good idea!

**Comment by kaie** [comment]
cross link: https://bugzilla.mozilla.org/show_bug.cgi?id=1652312

**Comment by ni4** [comment]
@kaie Could you please check whether just merged #1342 fits your needs? Thanks.
