### ISSUE TITLE
Duplicated function `test_rnp_list_packets` in CLI tests

### ISSUE THREAD

**Issue by antonsviridenko** [rnpgp/rnp#1201]
## Description

Function `test_rnp_list_packets` is defined twice in the same class 'Misc'. 

## Steps to Reproduce

1. https://github.com/rnpgp/rnp/blob/master/src/tests/cli_tests.py#L1536
2. https://github.com/rnpgp/rnp/blob/master/src/tests/cli_tests.py#L1611

## Expected Behavior

I think that second instance of this function was intended to have some different name and it was duplicated by mistake.

**Comment by ni4** [comment]
Yeah, second one should be named like `test_rnp_list_packets_edge_cases()`.
