### ISSUE TITLE
Portability issues

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#122]
See discussion in: https://github.com/riboseinc/rnp/pull/117

I guess the proper way to handle this is to update the autotools bits.
My knowledge there is lacking.
It defaults to --std=gnu99 locally for me, which is not quite enough for clang (gnu11 would probably work).

I should probably avoid overriding --std and defining _GNU_SOURCE explicitly in the CI scripts.

Some of the portability concerns I see are:

* `getpass`
* `mkstemp`
* `mkdtemp`
* `strcasemp`
* `MAP_FILE`
* `nftw`

**Comment by ronaldtse** [comment]
Aha so this is the list of portability concerns!

Let me add the following too mentioned in #9 .
* asprintf
* vasprintf

**Comment by dewyatt** [comment]
@ronaldtse This reminds me, do you have an official list of platforms we should aim to support?

**Comment by ronaldtse** [comment]
@dewyatt the official list of platforms is listed in the `README` now.

**Comment by ni4** [comment]
@dewyatt looks like these functions are removed or handled in other way, so should we close this now?

**Comment by dewyatt** [comment]
@ni4 Yes indeed
