### ISSUE TITLE
Better strategy for importing a big public key block?

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1273]
Although RNP has recently improved the memory allocation situation, it still requires a lot of RAM when processing a big public key block.

We see that users try to export all their public keys from GnuPG, and then try to import them to Thunderbird.

Ideally, it would be great to have a way to "split" the big key block that the user has exported, into smaller pieces, or even into individual keys, and then ask RNP to process each key individually.

Can you think of an easy way to perform this split?

**Comment by ni4** [comment]
@kaie I was thinking about changing of key import behavior as well. Initially it was designed to import single key/small amount of keys so loads all of them into temporary keyring.
Current idea is to add flag like RNP_LOAD_SAVE_IMPORT_FIRST, which would make rnp to read only first key with subkeys from the input, allowing to call function multiple times. That would also allow to update GUI with progress information/error messages and so on.

**Comment by ni4** [comment]
@kaie Once you have time, could you please check whether the new flag (RNP_LOAD_SAVE_SINGLE) for `rnp_keys_import()` satisfies your needs? Thanks!
