### ISSUE TITLE
Provide generic User ID filter for Key export, or WKD-export?

### ISSUE THREAD

**Issue by duckdalbe** [rnpgp/rnp#1285]
Would you be interested in implementing a generic User ID filter for Key export, or a specific WKD-suitable Key export?

In a Web Key Directory, keys must only include the one User ID that matches the email address they are provided for <https://tools.ietf.org/html/draft-koch-openpgp-webkey-service-09#section-5> (3rd paragraph).

I guess it might be not hard to add, because you already have code to select a User ID on export for autocrypt in `rnp_key_export_autocrypt()`. But that function strips all signatures (which is not desirable or should at least be optional), and all subkeys (which neither is desirable or should be optional) and ascii-armors the key (which is not appropriate for WKD). 

(I'm looking at RNP (actually: ruby-rnp) to maybe use it for a custom project which includes publishing keys to a WKD, thus I'm asking.)

**Comment by ni4** [comment]
@duckdalbe Thanks for the request. We definitely need to extend export function with extensible functionality - ability to strip unneeded userids, photos, expired/invalid or obsolete signatures and so on. This requires some thinking - once API is implemented it would be very very undesirable to change it later.

**Comment by ni4** [comment]
Related issue: #1006

**Comment by ni4** [comment]
@duckdalbe As of PR #1382 we have functions to remove userids and signatures. Will those fit your needs / could we close this issue?

**Comment by duckdalbe** [comment]
I guess this can be closed, yes. My work on the mentioned project is currently suspended, but next time I touch it and if these changes then have reached ruby-rnp I'll try to use them!

Thank you for caring! 👍
