### ISSUE TITLE
Allow absence of extra empty line in armored messages.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1289]
## Description

Currently we require an extra empty line after the armor header and between base64 data, i.e.
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQGNBFuJOtUBDACsrDfGPO9ZFB0TeFbAVJOkArNeBQtu/ShOSymuNrw+chhu8QtF
fHB935fc5AI1A0ls37DmSWnwhq8T06hpc8rBTZLTMkjutTUkBcUVbgPbyJSJzWEU
...
```

However, it doesn't seem to be strictly required by RFC, and GnuPG accepts data without an extra line:
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
mQGNBFuJOtUBDACsrDfGPO9ZFB0TeFbAVJOkArNeBQtu/ShOSymuNrw+chhu8QtF
fHB935fc5AI1A0ls37DmSWnwhq8T06hpc8rBTZLTMkjutTUkBcUVbgPbyJSJzWEU
...
```

**Comment by ni4** [comment]
@antonsviridenko Would you like to take this one together with #1381 ?

**Comment by antonsviridenko** [comment]
@ni4 I am unable to reproduce this behaviour using 
```
$ gpg --version
gpg (GnuPG) 2.2.20
libgcrypt 1.8.5
```
it prints errors like this
```
gpg: invalid armor header: mQENBFjyB/ABCADCN0R+oEmZwteTXgUrgbcp92UJYs57OOKQ0der2816uV/am6/K\n
```

**Comment by ni4** [comment]
@antonsviridenko just checked - while `gpg --import keyfile.asc` displays the warning about the invalid armor header, it still imports a key. Is it the same in your case?

I have gpg 2.2.26/libgcrypt 1.8.7

**Comment by antonsviridenko** [comment]
ok, it imports public key but fails to verify cleartext signature when empty line is removed

**Comment by ni4** [comment]
Probably that's because of the line `- Exactly one empty line not included into the message digest` in the RFC.
Then let's leave it as it is for the cleartext signature.

**Comment by ni4** [comment]
@antonsviridenko Did you have any chance to get back to this issue? Would be nice to close (as it doesn't seem to be hard to implement). If not I can take it.

**Comment by antonsviridenko** [comment]
ok, will try to take a look soon

**Comment by ni4** [comment]
> ok, will try to take a look soon

Thanks! Just to make things a bit more clear - this issue applies only to armored messages (keys, encrypted files, signatures), not to the cleartext signed data.

**Comment by antonsviridenko** [comment]
@ni4 I've run out of ideas how to implement this change. `armor_parse_headers()` is expected to skip possible header lines, empty line after the header and place read cursor at the beginning of Base64-encoded data. But if it starts reading base64 lines, it somehow has to "un-skip" them back, in order to return successful result while reporting 'unknown header error.

And we probably want to handle cases when unknown/invalid header is followed by valid header, something like
```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Invalid_header: invalid_value
Hash: SHA256

mQGNBFuJOtUBDACsrDfGPO9ZFB0TeFbAVJOkArNeBQtu/ShOSymuNrw+chhu8QtF
fHB935fc5AI1A0ls37DmSWnwhq8T06hpc8rBTZLTMkjutTUkBcUVbgPbyJSJzWEU
...
```

**Comment by antonsviridenko** [comment]
Maybe any line that does not contain colon `:` character can be considered as a data line and header parsing should stop there?

**Comment by ni4** [comment]
> Maybe any line that does not contain colon `:` character can be considered as a data line and header parsing should stop there?

@antonsviridenko base64 chars cannot include colon, so you may add some function `is_base64(...)`, and call it in `armor_parse_headers()`:
```C
      ...
        else if (hdrlen) {
            if (is_base64_line(header, hdrlen) {
               RNP_LOG("Warning: no empty line after the base64 headers");
               return true;
            }
            src_skip(param->readsrc, hdrlen);
            if (rnp::is_blank_line(header, hdrlen)) {
                return src_skip_eol(param->readsrc);
            }
        }
```
