### ISSUE TITLE
encrypted_add_recipient, !userkey->valid, attempt to use invalid key as recipient

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#1293]
When attempting to encrypt to a certain recipient key, RNP reports "attempt to use invalid key as recipient".

The failing check is in encrypted_add_recipient, if (!userkey->valid)

I couldn't find out what's wrong with the key.
For privacy reasons I'll send the key to Nickolay by email.

The key has a user ID that doesn't any spaces to separate name from email address. It looks like this:
```user@example.com<user@example.com>```

But that doesn't seem to be the issue, I created a fresh key with the same property, which works fine.

**Comment by kaie** [comment]
tracking also at
https://bugzilla.mozilla.org/show_bug.cgi?id=1663349

**Comment by ni4** [comment]
@kaie We've got some logic error here by incorrectly handling key expiration time in this case, when key expiration time subpacket is present in certification, but contains zero value. Will fix this. Possible workaround right now is to set key/subkey expiration time via GnuPG to some large value, say 20 years.

**Comment by kaie** [comment]
thanks, it's working
