### ISSUE TITLE
Should/could we use C++ type instead of POD for FFI structs?

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1303]
## Description

We have some structs inside of FFI objects which sooner or later will become "more C++" and could include other C++ objects, including containers.
As an example: `rnp_op_encrypt_t`, which includes `rnp_ctx_t`, which now has `list recipients`. At some point we'll change recipients to `std::list`, and it must be initialized via constructor.
So we would not be able to use calloc() to allocate memory for `rnp_op_encrypt_t`, and use `new` and constructor instead.

Is there any problem on moving to `new` from the `calloc()` for `rnp_op_encrypt_t`?
Or should we keep POD-style for FFI structs and use pointers to `rnp_ctx_t` inside instead?

CC @dewyatt @rrrooommmaaa @antonsviridenko

**Comment by ni4** [comment]
@antonsviridenko It doesn't as far as I know (and anyway we return pointer to opaque struct in API calls), but maybe I'm missing something deep/some possible side effect/whatever else.

**Comment by dewyatt** [comment]
Shouldn't be an issue and I would say it's definitely the way forward

**Comment by ni4** [comment]
Okay, thanks for replies!

**Comment by ni4** [comment]
Closing this as resolved (we already use some C++ types for FFI structs).
