### ISSUE TITLE
Expired OpenPGP Certificate not recognized as expired

### ISSUE THREAD

**Issue by nwalfield** [rnpgp/rnp#1311]
Consider the following key (attached):

```
$ sq packet dump primary-expired.pgp
Public-Key Packet, new CTB, 51 bytes
    Version: 4
    Creation time: 2020-09-18 11:57:00 UTC
    Pk algo: EdDSA Edwards-curve Digital Signature Algorithm
    Pk size: 256 bits
    Fingerprint: 8C7B 1E85 3474 17FC A304  D5EA E431 8B62 A47A A25C
    KeyID: E431 8B62 A47A A25C
  
Signature Packet, new CTB, 135 bytes
    Version: 4
    Type: DirectKey
    Pk algo: EdDSA Edwards-curve Digital Signature Algorithm
    Hash algo: SHA512
    Hashed area:
      Signature creation time: 2020-09-18 11:57:00 UTC (critical)
      Key expiration time: PT1S (critical)
      Symmetric algo preferences: AES256
      Hash preferences: SHA512
      Key flags: CS (critical)
      Features: MDC
    Unhashed area:
      Issuer: E431 8B62 A47A A25C
      Issuer Fingerprint: 8C7B 1E85 3474 17FC A304  D5EA E431 8B62 A47A A25C
    Digest prefix: 69F7
    Level: 0 (signature over data)
  
User ID Packet, new CTB, 45 bytes
    Value: Primary Expired <primary-expired@example.org>
  
Signature Packet, new CTB, 132 bytes
    Version: 4
    Type: PositiveCertification
    Pk algo: EdDSA Edwards-curve Digital Signature Algorithm
    Hash algo: SHA512
    Hashed area:
      Signature creation time: 2020-09-18 11:57:00 UTC (critical)
      Symmetric algo preferences: AES256
      Hash preferences: SHA512
      Primary User ID: true (critical)
      Key flags: CS (critical)
      Features: MDC
    Unhashed area:
      Issuer: E431 8B62 A47A A25C
      Issuer Fingerprint: 8C7B 1E85 3474 17FC A304  D5EA E431 8B62 A47A A25C
    Digest prefix: 1526
    Level: 0 (signature over data)
  
Public-Subkey Packet, new CTB, 56 bytes
    Version: 4
    Creation time: 2020-09-18 11:57:00 UTC
    Pk algo: ECDH public key algorithm
    Pk size: 256 bits
    Fingerprint: A587 FFD8 F64B 4C44 D6A1  CE9D ABAF 72C6 9B4B C2FF
    KeyID: ABAF 72C6 9B4B C2FF
  
Signature Packet, new CTB, 123 bytes
    Version: 4
    Type: SubkeyBinding
    Pk algo: EdDSA Edwards-curve Digital Signature Algorithm
    Hash algo: SHA512
    Hashed area:
      Signature creation time: 2020-09-18 11:57:00 UTC (critical)
      Key flags: EtEr (critical)
      Features: MDC
    Unhashed area:
      Issuer: E431 8B62 A47A A25C
      Issuer Fingerprint: 8C7B 1E85 3474 17FC A304  D5EA E431 8B62 A47A A25C
    Digest prefix: 5B6F
    Level: 0 (signature over data)
  
```

The direct key signature indicates that the primary key should expire 1 second after its creation.

rnp doesn't seem to think that the key is expired:

```
$ src/rnpkeys/rnpkeys --homedir=$T --import primary-expired.pgp
sec keyring '/tmp/tmp.MhdvXtVrFA/secring.gpg' is empty

pub   255/EdDSA e4318b62a47aa25c 2020-09-18 [SC]
      8c7b1e85347417fca304d5eae4318b62a47aa25c
uid           Primary Expired <primary-expired@example.org>
sub   255/ECDH abaf72c69b4bc2ff 2020-09-18 [E]
      a587ffd8f64b4c44d6a1ce9dabaf72c69b4bc2ff
```

and rnp doesn't have a problem encrypting to it:

```
$ src/rnp/rnp --homedir=$T --encrypt -r e4318b62a47aa25c foo.txt
File 'foo.txt.pgp' already exists. Would you like to overwrite it (y/N)? y
$ echo $?
0
```

gpg, however, rejects it as expired:

```
$ gpg --import primary-expired.pgp
gpg: key 0xE4318B62A47AA25C: public key "Primary Expired <primary-expired@example.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
$ gpg -e -r 0xE4318B62A47AA25C
gpg: 0xE4318B62A47AA25C: skipped: Unusable public key
gpg: [stdin]: encryption failed: Unusable public key
$ gpg -k 0xE4318B62A47AA25C
pub   ed25519/0xE4318B62A47AA25C 2020-09-18 [SC] [expired: 2020-09-18]
      Key fingerprint = 8C7B 1E85 3474 17FC A304  D5EA E431 8B62 A47A A25C
uid                   [ expired] Primary Expired <primary-expired@example.org>

```

Thunderbird 78.2.2 treats this key the same way.  That is, it doesn't consider it to be expired.

[key.zip](https://github.com/rnpgp/rnp/files/5245359/key.zip)

**Comment by ni4** [comment]
@nwalfield Thanks for reporting. Yeah, currently RNP checks for key expiration in the latest valid self-signature. Do you have a quick way to check whether things are changed for GnuPG if certification will include 0 key expiration subpacket? Or, be issued slightly after the direct-key signature?

Is there any strict logical rule how to behave in such non-obvious cases in RFC? I don't seem to recall any (except recommendation to pick information from the latest self-signature).

**Comment by nwalfield** [comment]
According to [Section 5.2.3.3](https://tools.ietf.org/html/rfc4880#section-5.2.3.3):

> subpackets on the direct-key signature apply to the entire key.
>
> Implementing software should interpret a self-signature's preference subpackets as narrowly as possible.

I interpret this as meaning: first check the self sig for the subpacket, then fallback to the direct key signature if it is not present.  Since the self sig doesn't have a Key Expiration subpacket, but the direct key signature does, the value in the direct key signature's subpacket should be used for determining the primary key's validity period.

If the primary key is expired, then the certificate should be considered invalid, because the signatures made by the primary are now invalid.

**Comment by ni4** [comment]
@nwalfield So basically direct-key signature and their contents would be of higher priority then self-certifications. 

What about the case, when direct-key signature is cut out and key is distributed by bad guy with non-expired certification only? Then all recipients will consider it as valid.

**Comment by nwalfield** [comment]
This is a consequence of OpenPGP's packet-based format.  An attacker could always withhold a revocation certificate, or an inconvenient self signature.  The only defense is to check for updates from multiple sources and hope that the attacker doesn't control all of the network paths.

**Comment by mkmelin** [comment]
Any update on this?

**Comment by ni4** [comment]
@mkmelin Didn't have a chance to get to it yet, but will prioritise.
