### ISSUE TITLE
Support utf-8/unicode in rnp_input_from_path() call.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1312]
## Description

Currently we do not interpret `char *path` parameter, and it works but only for ASCII paths (or, most likely, for paths which use system encoding).
If path contains any non-ASCII character, `rnp_input_from_path()` will fail, at least on Windows.

Possible solutions:
- assume that path* parameter is in utf-8 encoding in `rnp_input_from_path()`. However, this most likely will introduce incorrect behavior on non-utf8 *nix systems when non-utf8 path will be passed
- add function `input_from_path_ex()` with additional encoding parameter. This seems to overcoplicate things a bit, we should not support all of the possible encodings, at least yet.
- add some special processing if path in `rnp_input_from_path()` is prefixed with "utf8:" or "utf16:"
- another solution?

Related TB bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1665493

**Comment by rrrooommmaaa** [comment]
Should I take this immediately? I've done some work on translating `CreateProcessW` arguments (by `rnp`,`rnpkeys`)in another branch #1053. So it makes sense to create `input_from_path_ex` to allow passing through wide chars without re-encoding.

**Comment by ni4** [comment]
Sure, feel free to take this one.
