### ISSUE TITLE
Treat blank line according to RFC 4880 in cleartext signatures.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1381]
## Description

Currently we allow only really blank lines while parsing cleartext messages and computing signatures.
However, as per RFC 4880,  ` The blank line can either be zero-length or contain only whitespace, that is spaces (0x20), tabs (0x09) or carriage returns (0x0d).`.

We should change our behaviour accordingly.
Please see attached test message and a key, which expose this problem from the real world. Borrowed from the https://thunderbird.topicbox.com/groups/e2ee/Tdc01fcf0672d2234-M39a70a4d8bf54b2b919632fe

[Key file](https://github.com/rnpgp/rnp/files/5813950/autoaanetuk.txt)
[Cleartext signature](https://github.com/rnpgp/rnp/files/5813953/sig-embedded.txt)

**Comment by ni4** [comment]
@antonsviridenko Would you be interested in this task, as you worked with cleartext sigs/eols recently?

**Comment by antonsviridenko** [comment]
sure

**Comment by antonsviridenko** [comment]
@ni4 what is the best place in the source tree to put function like `is_blank_line(const char *line, size_t len)` (or `rnp_is_blank_line(const char *line, size_t len)`?

**Comment by ni4** [comment]
@antonsviridenko `str-utils.h`/`str-utils.cpp` ?

**Comment by antonsviridenko** [comment]
ok
