### ISSUE TITLE
Add --expiration flag to rnpkeys CLI

### ISSUE THREAD

**Issue by rrrooommmaaa** [rnpgp/rnp#1388]
## Description

Afaik, there is currently no way to set up key expiration when creating a key via `rnpkeys` CLI.

#323 says the flag should be called `--expires`.
UPD: let's call this flag `--expiration`

**Comment by rrrooommmaaa** [comment]
In GNUPG 
```
Several formats are supported; commonly the ISO formats “YYYY-MM-DD” or “YYYYMMDDThhmmss” are used. To make the key expire in N seconds, N days, N weeks, N months, or N years use “seconds=N”, “Nd”, “Nw”, “Nm”, or “Ny” respectively. Not specifying a value, or using “-” results in a key expiring in a reasonable default interval. The values “never”, “none” can be used for no expiration date.
```
Do we need to support all of these?

**Comment by ni4** [comment]
@rrrooommmaaa 
Hm, now it seems for me that `--expiration` would look better, what do you think?
There is a function `get_expiration()` in `rnpcfg.cpp` which may be used at the first implementation.
And, actually, it would be enough as it allows user to set any desired expiration time.

Another thing in this task is to check whether by default keys have meaningful expiration (like, 2 years).

**Comment by rrrooommmaaa** [comment]
> Hm, now it seems for me that `--expiration` would look better, what do you think?

Probably better, yes

**Comment by antonsviridenko** [comment]
Maybe `--set-expiration` has more explicit meaning?

**Comment by ni4** [comment]
> Maybe `--set-expiration` has more explicit meaning?

`--set-expiration` could be used to change expiration time of the already existing key/subkey.

**Comment by rrrooommmaaa** [comment]
> > Maybe `--set-expiration` has more explicit meaning?
> 
> `--set-expiration` could be used to change expiration time of the already existing key/subkey.

Yes, but there can't be both genkey and modify operations in one CLI call, right? So I'd vote to have a single constant for both cases

**Comment by rrrooommmaaa** [comment]
@ni4 There is also an issue when setting small expiration value (1 second). The generation is successful, but the signature creation timestamp is greater than key expiration (because it took more than 1 second for the process to complete). Some clients (`OpenPGP.js`) consider this to be an invalid signature. How does it conform to the RFC4880 standard. Should we prevent this situation from happening?

**Comment by ni4** [comment]
> Yes, but there can't be both genkey and modify operations in one CLI call, right? So I'd vote to have a single constant for both cases

In first case `--expiration/--set-expiration` is a parameter, in the second, `--set-expiration` - operation. So it may lead to some misunderstanding/complications.

> There is also an issue when setting small expiration value (1 second). 

This signature must be considered as invalid, does rnp mark this key as invalid?
I'd say let user play with it - this may be useful for some sort of debugging and tests creation.

**Comment by rrrooommmaaa** [comment]
> This signature must be considered as invalid, does rnp mark this key as invalid?
> I'd say let user play with it - this may be useful for some sort of debugging and tests creation.

Ok.
(I just wanted to create a key that is immediately expired, but I didn't want to create an invalid key and OpenPGP.js recognized that something is wrong with this key because of suspicious signature creation time)
