### ISSUE TITLE
shared library naming: why librnp-0 instead of librnp ?

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1406]
When I build with `-DBUILD_SHARED_LIBS=on` on a GNU/Linux platform, tag `v0.14.0` produces a shared object file named `librnp-0.so.0.14.0`.

We have the SONAME already present in the suffix after `.so` -- the first `.0` there is the `SONAME`.

What's the rationale for *also* having `-0` in the library name?   Has there been any thought to dropping it and just being `librnp`?  It seems simpler and cleaner, and would be easier to find.

Note that this is the same issue as the pkg-config file, which ends up as `librnp-0.pc` -- so users need to specify `pkg-config --libs --cflags librnp-0` instead of `pkg-config --libs --cflags librnp`.

Likewise, the header files for development show up in `/usr/include/rnp-0/rnp/rnp*.h` -- If they were placed directly in `/usr/include/rnp/rnp*.h` there wouldn't be any need for an extra `-I` argument during compilation.

I'm working on packaging for debian, and i'd prefer to have the binary package named `librnp0` and the development package named `librnp-dev` -- i think that's more easily discoverable, and should make it easier to [transition to an updated major version in the distro](https://release.debian.org/transitions/).  But with the current file naming scheme, i'm obliged to name the packages `librnp-0-0` and `librnp-0-dev`, which makes that all a bit clumsier.

Is the intent of including the major version number in the library name to preserve some sort of co-installability?  co-installability of the binary shared objects is already possible (based on the SONAME, which will surely be updated at least once per major version release)  That leaves me thinking that the intent is to preserve/facilitate co-installability of the development files.  But that doesn't seem like a great idea -- for example, i don't think anyone should want to build anything against two different major versions of rnp at once.

If there's a strong preference with a rationale for this duplicative versioning information, i'd be interested in knowing the rationale.  If there's no preference, but just no time/energy to make a change to the simpler arrangement, i would be happy to supply patches.  Let me know if i can help.

**Comment by dewyatt** [comment]
The rationale was pretty much as you speculated, mostly to make it clear which major version one was building against and to allow multiple major versions w/headers to be installed.

I do recall that when I initially implemented this I speculated we *may* want to drop it when releasing a stable 1.0.
Anyways, I'm ok with dropping it personally.

**Comment by dkg** [comment]
Thanks for the followup.

I don't think i understand the underlying rationale for the development headers part of this:

> allow multiple major versions w/headers to be installed.

Presumably, if the user is building software against an installed system library with development headers, they only want to be building against *one* major version of librnp at once.  Is there a situation where you'd want to build against two different versions of librnp concurrently? that sounds dangerous!

and, if it's not a system library (that is, if the user has manually installed it someplace) then the user can just place the  headers wherever they want and direct their compiler to find them appropriately.

(note that if you're talking about different major versions of the *binary* (not the development headers), that's already easy to co-install, because the `.so` has a versioned number in it its filename)

> drop it when releasing a stable 1.0

I think you'd likely be able to safely drop it before then, with the added benefit that you don't establish any expectation that the SONAME will be duplicated in the library name.  i'll try to send a patch.

**Comment by dewyatt** [comment]
It was inspired by botan initially, I liked the idea of providing something analogous to SONAME but for the API, allowing multiple system installations of different major versions of the library & headers. "If we support that on the binary side with SONAME, why not support it for the headers?" was sort of my view IIRC.
But again, I don't mind it changing either. I'll leave it for other devs to vote on.

**Comment by dkg** [comment]
I've just proposed #1417 as an example changeset that i think achieves this simplification.  It works for me -- but of course i won't apply it in debian if it's not something upstream is comfortable with.

If you decide not to make this change, you can just close that PR.

**Comment by ni4** [comment]
Agree with these changes.

**Comment by ronaldtse** [comment]
@dkg thanks for the suggestion, I agree it makes life a bit simpler for most users.
