### ISSUE TITLE
missing manpages for `rnp` and `rnpkeys`

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1407]
Debian encourages shipping manual pages for any binary shipped.  I aim to ship `/usr/bin/rnp` and `/usr/bin/rnpkeys` in an `rnp` package, but i don't have any manual pages to ship with them.

Do you have any plans to produce manual pages?  Man pages generated from the source code itself might be the best way to ensure that the docs are kept up-to-date, but manpages kept in sync with the code by hand can also be fine.  I can try to write some manual pages if that would be useful.  And i'd be happy to contribute them back upstream, especially if they'll be adopted!  If you want me to work on them, do you have a preferred source format and/or document-production workflow?

Left to my own devices with no additional guidance, the man pages I produce will likely be either hand-crafted troff or [pandoc-targeted markdown](https://www.pragmaticlinux.com/2021/01/create-a-man-page-for-your-own-program-or-script-with-pandoc/).  If you want me to work on it, please let me know if you prefer one of those choices (or something entirely different).

**Comment by dkg** [comment]
sorry, I now see the troff manpages already shipping (but not installed), in `src/rnp/rnp.1` and `src/rnpkeys/rnpkeys.1`.  I'll go ahead and use them directly.

You might want to try to have the default installation step install them as well.

**Comment by ni4** [comment]
This man pages are quite outdated, and still needs to be rewritten. I'll handle this via #506
