### ISSUE TITLE
intermittent test suite failures when run in parallel

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1408]
When i run the test suite for v0.14.0 in parallel on a machine with many cores, i get intermittent failures.

In particular, it looks like `cli_tests.py` is run multiple times concurrently, and sometimes two runs will try to produce the same output file at the same time.  During a failing test, i see this sort of output/warning fly by:

```
File '/tmp/x/rnp/build/src/tests/cleartext.rnp' already exists. Would you like to overwrite it (y/N)? Generating a new key...
```

I *want* to be able to run the test suite in parallel -- it's a large and comprehensive suite.  But i'm forced to run it serially to avoid these intermittent failures.

**Comment by dewyatt** [comment]
This is a (probably undocumented) bug that occurs when the rnp build directory is in `/tmp`.

**Comment by dkg** [comment]
i can confirm that i've only seen these failures when the build directory is in `/tmp`, but i'm mystified as to why that should be the case.  can you explain more?

**Comment by dewyatt** [comment]
> i can confirm that i've only seen these failures when the build directory is in `/tmp`, but i'm mystified as to why that should be the case. can you explain more?

It's likely to be from:
https://github.com/rnpgp/rnp/blob/c04acfda7b5faf6bec2960cb8156fd93362411b0/src/tests/cli_tests.py#L751-L753

**Comment by dkg** [comment]
thanks for the pointer.  #1420 appears to resolve the issue for me.
