### ISSUE TITLE
simplify build for shared library without ruby tests

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1409]
I'm building the initial debian packaging for rnp, and i'm building with `DBUILD_SHARED_LIBS=on`.  We don't have `ruby-rnp` available on that system yet (chicken and egg problem).

So i'm currently [patching out](https://salsa.debian.org/debian/rnp/-/blob/debian/main/debian/patches/0002-Avoid-tests-for-ruby-rnp.patch) the attempt to test `ruby-rnp` against the newly-built library -- and in the future, for bootstrapping stuff in debian generally, we'd also like to be able to build without requiring ruby-rnp be available.  If it is possible to add a new configure option (or something comparable) to build without testing `ruby-rnp` that would be great.

This line in particular in `src/tests/CMakeLists.txt` seems like it is a good candidate for a place to add an additional controlling variable:

```
if (NOT ENABLE_SANITIZERS AND BUILD_SHARED_LIBS AND NOT WIN32)
```

**Comment by ni4** [comment]
Related issue  #1267

**Comment by dkg** [comment]
Thanks for pointing to #1267, i'd missed that.  That report seems to have more useful detail, so I followed up over there, and i'm closing this report in favor of that one.
