### ISSUE TITLE
packaging / bug report e-mail bounces

### ISSUE THREAD

**Issue by andreasstieger** [rnpgp/rnp#1423]
## Description

`rnp` asked for bug reports to be sent to `packaging@ribose.com`. This e-mail address bounces.
https://github.com/rnpgp/rnp/blob/d440935cd257457afc865413070f7b4c4373c535/cmake/info.cmake#L29
https://github.com/rnpgp/rnp/blob/7fbb6f78939b9cf9a182be238334a51b9c35297f/src/lib/config.h.in#L28
https://github.com/rnpgp/rnp/blob/11bd963fedf86f63f2962c088ca1af4df8814a38/src/rnp/rnp.cpp#L223-L225

## Steps to Reproduce

1. `rnp --version`

## Expected Behavior

Link to a working e-mail address, or github issue link.

## Actual Behavior

A bouncing e-mail address.

**Comment by dkg** [comment]
Thanks @andreasstieger for raising this. Fixing this up is important for Debian as well.  If there's a particular preferred reporting/contact path, it'd also be nice for that to be publicized consistently across the source and documentation.

**Comment by andreasstieger** [comment]
I'd say to point it to https://github.com/rnpgp/rnp/issues by default, and make it configurable for a distribution-specific packaging bug report contact.

**Comment by ni4** [comment]
@ronaldtse whom should be pinged for the email? Also I think that another one is needed for the security issues, which should not get into the public repository.

**Comment by dkg** [comment]
While you're thinking about security issue reporting, please ensure that the security issue e-mail address has a well-known OpenPGP certificate that can be used to receive encrypted reports.  in addition to the usual venues for cert distribution (SKS, keys.openpgp.org, WKD), you should also ship the certificate in the rnp source code so that anyone who has the source can report issues without needing to investigate further to dig up keys.

**Comment by ronaldtse** [comment]
Let's change to rnpgp@ribose.com . This email is only intended for non-security reporting purposes. Will follow up on security reporting.

**Comment by ronaldtse** [comment]
Bug reports should be sent to the GitHub issue tracker, as suggested by @andreasstieger (thanks!).

**Comment by ronaldtse** [comment]
This is fixed in #1458.

**Comment by ni4** [comment]
> This is fixed in #1458.

So I assume we may close this issue?

**Comment by ni4** [comment]
...hm, nope, as we didn't update PACKAGING_EMAIL in the sources.

**Comment by ni4** [comment]
Fixed via #1475
