### ISSUE TITLE
rnp build failures on 32-bit platforms on debian

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1436]
rnp landed in debian unstable yesterday.

It's now building (or trying to build) on all of debian's supported architectures.

[you can see an overview](https://buildd.debian.org/status/logs.php?arch=&pkg=rnp) -- but the short  version is that while most 64-bit platforms appear to succeed, it looks like all of the 32-bit platforms are failing.  You can [learn more about the different platforms](https://wiki.debian.org/ArchitectureSpecificsMemo) if you want.

For example, [i386 fails](https://buildd.debian.org/status/fetch.php?pkg=rnp&arch=i386&ver=0.14.0-4&stamp=1614529998&raw=0) with:

```
pub   1024/DSA 2fcadf05ffa501bb 2017-07-20 [SC] [EXPIRED 1947-04-04]
      be1c4ab951f4c2f6b604c7f82fcadf05ffa501bb
uid           key1-uid0
uid           key1-uid2
uid           key1-uid1
sub   1024/Elgamal (Encrypt-Only) 54505a936a4a970e 2017-07-20 [E] [EXPIRED 1947-04-04]
      a3e94de61a8cb229413d348e54505a936a4a970e
sub   1024/Elgamal (Encrypt-Only) 326ef111425d14a5 2017-07-20 [E]
      57f8ed6e5c197db63c60ffaf326ef111425d14a5
ERROR
/usr/bin/gpgconf --homedir /tmp/rnpctmpk8dq2e5f/.gpg --kill gpg-agent



======================================================================
ERROR: test_rnp_permissive_key_import (__main__.Misc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/src/tests/cli_tests.py", line 1646, in test_rnp_permissive_key_import
    compare_file_ex(data_path('test_cli_rnpkeys/pubring-malf-cert-permissive-import.txt'), out,
  File "/<<PKGBUILDDIR>>/src/tests/cli_tests.py", line 194, in compare_file_ex
    raise_err(message)
  File "/<<PKGBUILDDIR>>/src/tests/cli_common.py", line 35, in raise_err
    raise CLIError(msg, log)
cli_common.CLIError: <unprintable CLIError object>

======================================================================
ERROR: test_rnpkeys_lists (__main__.Misc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/src/tests/cli_tests.py", line 1469, in test_rnpkeys_lists
    compare_file(path + 'keyring_1_list_keys', out, 'keyring 1 key listing failed')
  File "/<<PKGBUILDDIR>>/src/tests/cli_tests.py", line 186, in compare_file
    raise_err(message)
  File "/<<PKGBUILDDIR>>/src/tests/cli_common.py", line 35, in raise_err
    raise CLIError(msg, log)
cli_common.CLIError: <unprintable CLIError object>

----------------------------------------------------------------------
Ran 19 tests in 83.830s

FAILED (errors=2)

211/213 Test #213: cli_tests-SignDefault .........................................................   Passed   47.34 sec
212/213 Test #204: cli_tests-Compression .........................................................   Passed  414.94 sec
213/213 Test #212: cli_tests-Encryption ..........................................................   Passed  820.16 sec

99% tests passed, 1 tests failed out of 213

Total Test time (real) = 1010.13 sec

The following tests FAILED:
	210 - cli_tests-Misc (Failed)
```

(this is noted in debian as [#983770](https://bugs.debian.org/983770)

**Comment by dkg** [comment]
fwiw, that first failure looks like a y2k38 issue -- claims `[EXPIRES 2083-05-11]` for `2fcadf05ffa501bb`, and the above shows `[EXPIRED 1947-04-04]`

**Comment by dkg** [comment]
A suggestion from a friend:

> perhaps something the code could be doing at run-time is checking whether it can round-trip the time conversion values.  Then disabling the test case would not be such an issue.

any sort of check for overflow for the internal representations would be a useful check, and it could be used to indicate that failures of specific marked tests could be ignored.

**Comment by ni4** [comment]
Looks like the source of problem is here:
```
    if (expiry > 0) {
        time_t now = time(NULL);
        time_t expire_time = create + expiry;
        ptimestr(buf, sizeof(buf), expire_time);
        fprintf(fp, " [%s %s]", expire_time <= now ? "EXPIRED" : "EXPIRES", buf);
    }
```

@antonsviridenko Would you like to take a look on this? Or perhaps @rrrooommmaaa ?

**Comment by rrrooommmaaa** [comment]
As I understood, `glibc` supplies `time_t` as 32-bit on (some) 32-bit systems.
Is using this library https://www.boost.org/doc/libs/1_65_1/doc/html/date_time/posix_time.html
an acceptable alternative for systems where `sizeof(time_t) < sizeof(int64_t)`?

**Comment by ni4** [comment]
@rrrooommmaaa We have issue #1048 to introduce Boost into the project. However, within recent issues about offline builds and so on it could overcomplicate this exact issue. I think usage of uint64_t on 32-bit platforms for the aforementioned calculations would be pretty enough.
@ronaldtse  @dewyatt thoughts?

**Comment by rrrooommmaaa** [comment]
`uint64_t` is of course enough, the question is: how to convert it to `tm` structure?

**Comment by ni4** [comment]
@rrrooommmaaa Missed that thing. Not sure what would be the better approach - looks like 32-bit `time_t` will be used for at least 3-5 years. Boost sources have lines like `::std::time_t t;` i.e. I assume (maybe wrong) that those are also rely on the system's `time_t`.

**Comment by rrrooommmaaa** [comment]
Looks like `time_duration` is 64-bit and we can convert it to `tm` or string.

**Comment by ni4** [comment]
@rrrooommmaaa it is, but it still seem to rely on system's `gmtime()`. Also I'm concerned with timezone data files there - we may end up with bringing problems to the 99% of working systems in attempt to fix things for 1%. Basically, it is impossible to bring correct `gmtime()` functionality without timezone database files, which are usually shipped by the system.

In this case, as a fast and non-breaking solution, we may just limit key expiration time on 32-bit systems to the year 2038, and update tests accordingly.

**Comment by ronaldtse** [comment]
Agree with @ni4 for an interim solution that is a documented limitation.

**Comment by rrrooommmaaa** [comment]
> In this case, as a fast and non-breaking solution, we may just limit key expiration time on 32-bit systems to the year 2038, and update tests accordingly.

I was going to suggest to output something like ">2038-01-01" in `ptimestr()` if we have overflow situation on 32-bit `time_t`.

**Comment by ni4** [comment]
> I was going to suggest to output something like ">2038-01-01" in `ptimestr()` if we have overflow situation on 32-bit `time_t`.

Sounds good to me.

**Comment by rrrooommmaaa** [comment]
I can take this after having finished with my current PR #1392 
if there is nothing urgent for me

**Comment by ni4** [comment]
@rrrooommmaaa If it is possible i'd suggest to prioritise this one as it is the only issue blocking v0.15.0 release.

**Comment by rrrooommmaaa** [comment]
we don't have any failing GHA builds configured, do we?

**Comment by ni4** [comment]
@rrrooommmaaa Yeah, as we don't have 32-bit Debian-based CI, so part of this task would be to add one :) Please see the first comment on this issue.

**Comment by ni4** [comment]
@rrrooommmaaa for the CI you may copy `centos7.yml`, changing container to any debian on 32bit architecture with linux kernel older then 5.6 (or 5.1?). `i386/debian:9` or/and `arm32v7/debian:9`  should work.
