### ISSUE TITLE
s390x and sparc64 "failures" in s2k_iteration_tuning : ratios < 6

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1439]
in the [s390x debian build](https://buildd.debian.org/status/fetch.php?pkg=rnp&arch=s390x&ver=0.14.0-6&stamp=1614653756&raw=0), with #1419 applied, the `s2k_iteration_tuning` test fails with a ratio of ~1.8:

```
 15/213 Test  #15: rnp_tests.s2k_iteration_tuning ................................................***Failed    0.51 sec
Note: Google Test filter = rnp_tests.s2k_iteration_tuning
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from rnp_tests
[ RUN      ] rnp_tests.s2k_iteration_tuning
./src/tests/cipher.cpp:665: Failure
Expected: ((static_cast<double>(iters_100) / iters_10)) > ((6)), actual: 1.82353 vs 6
[pgp_s2k_compute_iters() ./src/lib/crypto/s2k.cpp:178] failed to create hash object
[  FAILED  ] rnp_tests.s2k_iteration_tuning (506 ms)
[----------] 1 test from rnp_tests (506 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (506 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] rnp_tests.s2k_iteration_tuning

 1 FAILED TEST
```

on the [sparc64 buildd](https://buildd.debian.org/status/fetch.php?pkg=rnp&arch=sparc64&ver=0.14.0-6&stamp=1614655232&raw=0) we see a ratio of ~4.4:

```
 31/213 Test  #15: rnp_tests.s2k_iteration_tuning ................................................***Failed    0.64 sec
Note: Google Test filter = rnp_tests.s2k_iteration_tuning
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from rnp_tests
[ RUN      ] rnp_tests.s2k_iteration_tuning
./src/tests/cipher.cpp:665: Failure
Expected: ((static_cast<double>(iters_100) / iters_10)) > ((6)), actual: 4.42857 vs 6
[pgp_s2k_compute_iters() ./src/lib/crypto/s2k.cpp:178] failed to create hash object
[  FAILED  ] rnp_tests.s2k_iteration_tuning (621 ms)
[----------] 1 test from rnp_tests (621 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (621 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] rnp_tests.s2k_iteration_tuning

 1 FAILED TEST
```

I've asked the buildds to retry the package on those architectures, but in previous versions (before #1419 was applied) we also saw repeated failures on them in this tuning test.

It seems possible that something about the tuning calculation is different on these different platforms -- either the hardware does some kind of more intensive parallelism, or the particular build daemons used are under heavy, jittery load.

I really appreciate that y'all have this test in place -- it's the right way to validate any assumptions that the code makes about s2k tuning.

If y'all have any thoughts or suggestions about what to do about this, i'm open to them.

**Comment by dkg** [comment]
it's also possible that given the limits of the range of s2k iterations, and the power of modern hardware, that we just want to ignore the tuning and always turn it up to the maximum.

**Comment by ni4** [comment]
`pgp_s2k_compute_iters()` uses `:gettimeofday()`, and quick reading tells that it's not the best solution. Looks like we should switch to the `clock_gettime` at some point.
Periodically it fails on macOS CI builds as well.

**Comment by Apteryks** [comment]
I have this test failing on x86_64 on GNU Guix, testing the latest 0.17.1 release.

**Comment by ni4** [comment]
@Apteryks thanks for letting us know! There is a `-DS2K_MINIMUM_TUNING_RATIO` which would adjust the ratio, does it help you?
