### ISSUE TITLE
Release version 0.15.0

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1447]
## Description

It looks like the time to release version 0.14.1, as we finished work on man pages and offline builds support, which would help package maintainers.
The only thing left unmerged, as I see, is #1417 

@rnpgp/developers  do you see any other issues which we should finish before releasing 0.14.1?

**Comment by ni4** [comment]
@ronaldtse  As from https://github.com/rnpgp/rnp/pull/1417#issuecomment-792747264, any objections on releasing v0.15.0 instead of v0.14.1?

**Comment by dewyatt** [comment]
Sounds good to me!

**Comment by ronaldtse** [comment]
Fully agree with 0.15.0!

**Comment by dkg** [comment]
has any attention been given to #1436?  i don't want to block a 0.15.0 release on them, but ensuring the CI passes on 32-bit systems (or at least systems with a 32-bit `time_t`) seems like it would be a worthwhile thing to consider.

**Comment by ni4** [comment]
> has any attention been given to #1436? i don't want to block a 0.15.0 release on them, but ensuring the CI passes on 32-bit systems (or at least systems with a 32-bit `time_t`) seems like it would be a worthwhile thing to consider.

Thanks for your suggestion (and sorry for a bit late reply). This was fixed via PR #1459, and just today version 0.15.0 of RNP was released, so closing this issue.

cc @kaie
