### ISSUE TITLE
Support Gentoo 

### ISSUE THREAD

**Issue by antonsviridenko** [rnpgp/rnp#1467]
## Description

Inspired by #1431. I can create Gentoo ebuild package for RNP and try to push it into the main Gentoo package repository or put it into the 3rd party repository (overlay in Gentoo terms). If there is some interest.

Gentoo is a GNU/Linux source based distribution.

**Comment by ronaldtse** [comment]
@antonsviridenko agree. Please feel free to go for it!

**Comment by antonsviridenko** [comment]
Great

@ronaldtse I have another similar idea, lets add RNP to the Buildroot packages too. Buildroot is very popular tool for building firmware images for embedded platforms.

https://buildroot.org/

**Comment by antonsviridenko** [comment]
@ronaldtse can this https://github.com/rnpgp/rnp/releases be considered as an official source of release tarballs? Or it's better to checkout by release tags from the git repository?

**Comment by ronaldtse** [comment]
@antonsviridenko I think we want to synchronise the tarballs and the release tags. For packaging purpose the tarballs should probably be considered the "source".

**Comment by antonsviridenko** [comment]
https://github.com/gentoo/gentoo/pull/20438

**Comment by antonsviridenko** [comment]
Looks like Gentoo developers are not interested in adding this new package into the main repository yet. Probably we'll have to create our own private repository (overlay in Gentoo terms) instead.

**Comment by ni4** [comment]
Probably we may re-ping them once v0.15.2 is released.

**Comment by antonsviridenko** [comment]
https://github.com/gentoo/api-gentoo-org/pull/418

**Comment by antonsviridenko** [comment]
ok, now our Gentoo overlay https://github.com/rnpgp/gentoo-rnp
is listed in official list of ovelays at https://overlays.gentoo.org/
and can be added by Gentoo users using
**layman** or **eselect-repository** tools.

**Comment by ronaldtse** [comment]
Thank you @antonsviridenko ! Added you as a maintainer so you have full access to the packaging workflows.

**Comment by ronaldtse** [comment]
@antonsviridenko as suggested https://github.com/gentoo/api-gentoo-org/pull/418#issuecomment-894673984 perhaps we should try adding the package to GURU?

**Comment by antonsviridenko** [comment]
@ronaldtse yeah, going to try this way too

**Comment by antonsviridenko** [comment]
Looks like contributing to GURU requires bit more efforts than expected (pull requests from GitHub are not accepted),
and for end users it takes exactly same amount of efforts to install RNP package from third party repo, does not matter if it is named 'GURU' or 'rnp', but we have full control over our own repository.

**Comment by ronaldtse** [comment]
@antonsviridenko how's this going?

**Comment by ni4** [comment]
@antonsviridenko Could this be closed now, or we still miss something Gentoo-related?

**Comment by antonsviridenko** [comment]
I've just discovered that RNP package is present in Gentoo main repository since 2022-08 under the name `librnp`.
https://packages.gentoo.org/packages/dev-util/librnp
added by Gentoo Mozilla Team,
so yes, can be closed I think.

**Comment by ronaldtse** [comment]
@antonsviridenko the Gentoo `librnp` package only uses Botan though.

Generally, should we need to (do we need to) differentiate Botan vs OpenSSL usage in distro packages?

**Comment by antonsviridenko** [comment]
Actually their version is bit more advanced and supports both, OpenSSL and Botan. Botan is selected as default option.

Generally Gentoo is about choice, and user should be able to select any possible combination of build dependencies. For other distros it could be decided by maintainer of the package, which one (Botan or OpenSSL) is more convenient for them and distro users.

**Comment by ni4** [comment]
So closing this.

**Comment by ronaldtse** [comment]
Thank you @antonsviridenko !
