### ISSUE TITLE
Fix inconsistency between rnp_key_export_autocrypt() and find_suitable_key().

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1470]
## Description

Function find_suitable_key() was fixed in the PR #1318 to return latest encrypting subkey, however rnp_key_export_autocrypt() still returns first encrypting subkey. While it is possible to pick subkey automatically, it still should reuse find_suitable_key(). Some boolean flag could be added like 'no_primary', so it will search subkeys only.
May be related or implemented together with #1457

**Comment by antonsviridenko** [comment]
> return latest encrypting subkey, however rnp_key_expory_autocrypt() still returns first encrypting subkey.

@ni4 What is the sorting order based on? Key creation time?

**Comment by ni4** [comment]
@antonsviridenko Please use `find_suitable_key()` with `PGP_KF_ENCRYPT` for that, so everywhere we use the same approach.
