### ISSUE TITLE
Explicitly enable or disable building man pages in cmake configuration

### ISSUE THREAD

**Issue by antonsviridenko** [rnpgp/rnp#1481]
## Description

As man pages are built using `asciidoctor`, current implementation just tries to autodetect presence of `asciidoctor` and depending on result either builds manpages or not. Now I am trying to create package for source-based Gentoo distro, and there building documentation is optional and configurable part, depending on user preferences. If user enables `doc` USE-flag either globally or specifically for this package, documentation will be built. And if it is enabled, additional build-time dependency (`asciidoctor` package in this case) should be pulled and installed first. So configuration of rnp build should be more deterministic. I propose to add new cmake variable like `ENABLE_DOC` or `ENABLE_MANPAGES`

## Expected Behavior

If documentation build is explicitly enabled (like -DENABLE_DOC=On), cmake should check for presence of `asciidoctor` and fail to continue if `asciidoctor` is not found. If it is explicitly disabled, then it should not check for `asciidoctor` at all and skip building manpages. Third option (like ENABLE_DOC=Auto) can be implemented and set as a default value in order to keep the current behavior.

## Actual Behavior

`asciidoctor` presence is automatically detected during build and there is no way to disable it or strictly require this dependency for succesfull build

**Comment by ronaldtse** [comment]
@antonsviridenko agree with your approach with `ENABLE_DOC`, please continue, thanks 😉
