### ISSUE TITLE
Do not mark signatures as invalid if key is expired. 

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1495]
## Description

If key is valid when data signature is created, then signature should be marked as valid even after key is expired or revoked.
This functionality should go to FFI and CLI, most likely via the helper function like `pgp_key_t->valid_at(timestamp)`.

**Comment by nwalfield** [comment]
Only if the key is soft revoked.  If the key is hard revoked (reason for revocation: compromised, unknown), then it should be considered invalid as an attacker could have pre-dated the signature.  See also https://docs.sequoia-pgp.org/sequoia_openpgp/types/enum.RevocationType.html#variants .

**Comment by ni4** [comment]
Thanks. Is soft/hard revocation is some common term used in the OpenPGP world? As I didn't see it before, just things described in https://tools.ietf.org/html/rfc4880#section-5.2.3.23 , like compromised/superseded/etc.

**Comment by nwalfield** [comment]
The RFC doesn't use those terms, but they are useful for distinguishing how a program should handle a revocation.  For the most part the consequences of the different soft revocations (1 and 3) are the same, and the same goes for the consequences of the different hard revocations (0, 2, >3).
