### ISSUE TITLE
Investigate streamlining CI processes to reduce time on cross-platform debugging

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1508]
From @ni4: 

> Could we just create Docker containers with all installed pre-requisites, and use them (updating periodically) for CI instead of running complicated scripts each time/spending time on debugging?

_Originally posted by @ni4 in https://github.com/rnpgp/rnp/issues/1501#issuecomment-845982728_

**Comment by maxirmx** [comment]
This is done in #1968
