### ISSUE TITLE
GnuPG (sometimes) does not build on CentOS 8

### ISSUE THREAD

**Issue by ribose-jeffreylau** [rnpgp/rnp#1522]
## Description

In the CI environment, certain combinations of env vars would cause GnuPG to not build on CentOS 8.

(And in the case of Fedora 33, almost none of the combinations would build.)

## Steps to Reproduce

1. Build GnuPG v2.3.0-beta983, Revision: c6702d77d (50800) on CentOS 8 container with `BUILD_MODE=sanitize` and `GPG_VERSION=beta`

## Expected Behavior

No build errors.

## Actual Behavior

https://github.com/rnpgp/rnp/runs/2743586062#step:8:4808

```
<snip>
libcommon.a(libcommon_a-iobuf.o):(.bss+0x8): multiple definition of `iobuf_debug_mode'
t-iobuf.o:(.bss+0x0): first defined here
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [Makefile:1047: t-iobuf] Error 1
make[2]: *** [Makefile:954: all] Error 2
make[1]: *** [Makefile:615: all-recursive] Error 1
make: *** [Makefile:535: all] Error 2
Error: Process completed with exit code 2.
```

**Comment by maxirmx** [comment]
Closing it since new CI uses different build sequence with prebuilt Fedora and CentOS containers that include selected gpg versions
