### ISSUE TITLE
When `~/.gnupg` exists without `~/.rnp`, rnpkeys reads the former for default key but does not load other keys

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1558]
## Description

This is from v0.15.1.

```sh
# ~/.gnupg exists with keys, ~/.rnp doesn't exist
$: rnpkeys --list-keys
rnp: default key set to "333C4477426DC542610211FB5719063A2D8998FA"
wrong pubring path
Key(s) not found.
```

Once I move away `~/.gnupg`, it works properly.
```
$: mv ~/.gnupg{,.bak}
$: rnpkeys --list-keys
wrong pubring path
Key(s) not found.
```

Question: Should we support only a single key directory or multiple?

rnpkeys should do one or multiple of the following:

1. Display a message on which key directory it is loading from ("Keyring detected at path ~/.gnupg/secring.gpg, using it")

2. When `~/.gnupg` exists, there are a few modes of operation (we need to discuss)
    * only operate from `~/.gnupg/`, perhaps give a warning: "WARNING: RNP loading non-native keyring from `~/.gnupg`. To migrate to the native RNP key collection format, run `rnpkeys import --home=~/.gnupg`".
    * prompt the user to migrate to `~/.rnp` and leave `~/.gnupg` alone in case we break something there.
    * Tell user in order to use `~/.gnupg` as directory they will need to configure a setting or always use `rnpkeys --homedir=~/.gnupg [command]`

**Comment by ni4** [comment]
@ronaldtse `default key set to` message comes from parsing of `gpg.conf`. I suggest to change logic to the following:
- if there is `~/.rnp` directory, or `--homedir` parameter, then use it (detecting the the contents type automatically)
- if there is no `~/.rnp` but there is `~/.gnupg` (i.e. most likely first run), then ask user what does he want:
    - import GnuPG keys to the RNP keyrings and work with them
    - use GnuPG keys in read-only mode
    - exit
- if there is no `~/.rnp` and no `~/.gnupg` then create empty `~./rnp` directory and show message like `Key storage directory created. Keyrings are empty - use rnpkeys --generate to create a new keypair.`

What do you think?

**Comment by ni4** [comment]
ping @ronaldtse

**Comment by ronaldtse** [comment]
> probably it would be good idea to stay aside from reading GnuPG key database directly as it's format may change. Better tell user about possibility to export/import.

@ni4 thanks for the reminder on this -- yes I agree with the approach. Fiddling with the GnuPG key database is definitely not something we want to do; using it in read-only mode (and prompting import) is acceptable.
