### ISSUE TITLE
Remove 3DES and SHA1 from the default generated key preferences.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1565]
## Description

While SHA1 is must not to use, 3DES is a bit obsolete and replaced by AES.

**Comment by ni4** [comment]
@rnpgp/developers Do you have any input on this? Or should we leave 3DES for the compatibility reasons? Given that even GnuPG just issues a warning if symmetric algorithm is not in recipient's preferences.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau I think we should still support 3DES and SHA-1 (to read old data), but not list them in the default key preferences?

**Comment by ribose-jeffreylau** [comment]
@ronaldtse I would think so too, just don't list them in the default generated key preferences list.

**Comment by ni4** [comment]
Thanks for the feedback. So closing it back.
