### ISSUE TITLE
CLI: display list of supported algorithms and backend in --version

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1594]
## Description

Currently it just displays version, while it would be also usable to have more detailed information on enabled algorithms and used backend.

**Comment by antonsviridenko** [comment]
Just a side note, I see that version information is printed to stderr, isn't stdout more suitable for this info?

**Comment by ni4** [comment]
@antonsviridenko yeah, stdout is more suitable for this, thanks.

**Comment by antonsviridenko** [comment]
Also version printing code is duplicated in `rnp` and `rnpkeys`, function `print_praise()` is identical in both programs but exists in two instances. Could be unified.

**Comment by ni4** [comment]
> Also version printing code is duplicated in `rnp` and `rnpkeys`, function `print_praise()` is identical in both programs but exists in two instances. Could be unified.

Definitely, it may be moved to `fficli.h/cpp`.

**Comment by antonsviridenko** [comment]
@ni4 which algorithms exactly should be listed in output?

**Comment by ni4** [comment]
> @ni4 which algorithms exactly should be listed in output?

Please see `gpg --version` for reference.
We have public key, symmetric, hash and AEAD algorithms at the moment. Also additionally we may list supported curves.

**Comment by antonsviridenko** [comment]
@ni4 I thought about iterating alogithm arays in https://github.com/rnpgp/rnp/blob/master/src/lib/rnp.cpp#L156
like `pubkey_alg_map[]` and printing out each item name,
but looks like they are not enclosed in macros like `#if defined(CRYPTO_BACKEND_XXX)` so it may print algorithms that actually are not supported by current backend.

**Comment by ni4** [comment]
@antonsviridenko Those are internals, and should not be used in the CLI. You should use FFI function `rnp_supported_features()` which takes care of ifdefs and so on. If it doesn't fit please feel free to let me know.

**Comment by antonsviridenko** [comment]
yes, right, I forgot about `rnp_supported_features()`
