### ISSUE TITLE
Check for the OpenSSL available features when configuring

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1595]
## Description

Currently OpenSSL backend automatically disables all non-default features, however we should check for available ones for better flexibility.

**Comment by ni4** [comment]
Required CMake module was added via PR #1692 , so now we should only check whether automatically disabled features are available.

**Comment by ni4** [comment]
@andrey-utkin Also within fixing of this issue we could drop check from CMake which allows to build with OpenSSL in the debug mode.

**Comment by ronaldtse** [comment]
Agree with @ni4. Thanks @andrey-utkin !

**Comment by andrey-utkin** [comment]
A spec by @ni4 
> WIthin automatic feature detection we should by default use 'Auto' mode, when only supported by backend features are enabled. However, allow user to enable or disable desired features via the corresponding CMake options, throwing an error if user wants to enable unsupported by backend feature.

https://github.com/rnpgp/rnp/pull/1875#issuecomment-1181885579

Which I understand as follows:
No configuration flags:
Backend is Botan, check that core depended features are present, all flag-features available in installed Botan are enabled.

backend=botan: same as above

backend=openssl: check that core depended features are present, all flag-features available in installed OpenSSL are enabled.

Above + specific ENABLE_* features set: specific features override autodetected values.

**Comment by ni4** [comment]
> A spec by @ni4
> 
> > WIthin automatic feature detection we should by default use 'Auto' mode, when only supported by backend features are enabled. However, allow user to enable or disable desired features via the corresponding CMake options, throwing an error if user wants to enable unsupported by backend feature.
> 
> [#1875 (comment)](https://github.com/rnpgp/rnp/pull/1875#issuecomment-1181885579)
> 
> Which I understand as follows: No configuration flags: Backend is Botan, check that core depended features are present, all flag-features available in installed Botan are enabled.
> 
> backend=botan: same as above
> 
> backend=openssl: check that core depended features are present, all flag-features available in installed OpenSSL are enabled.
> 
> Above + specific ENABLE_* features set: specific features override autodetected values.

Yeah, correct.

P.S. Do you really have a need to address issue in the commit title? It makes issue's comment log quite unreadable.

**Comment by andrey-utkin** [comment]
I feel I do! It's a widespread practice and I'm glad for it, as software archeology is a regular part of the job :)
I don't know how to leave a link to the issue ticket in a commit message so that github doesn't pick it up but that it's not too obscure/tedious for people to pick up.
Sorry for the readability issue. Indeed it clutters the issue page, wait until github starts to fold it up! FWIW, emails from github provide an alternative view of the discussion.

**Comment by ni4** [comment]
> I don't know how to leave a link to the issue ticket in a commit message so that github doesn't pick it up but that it's not too obscure/tedious for people to pick up.

Having issue number with hashtag in the PR message (as well as some description on what's going on there) instead of title would not create comment on each force-pushed commit (and would display link to the PR which addresses this issue to the right). Would this work for the arechological purposes?

**Comment by andrey-utkin** [comment]
It would work great if we agree to merge PRs with proper merge commits, not by rebasing. This way there'll be a full trace - from commit to the merge, and from merge to the ticket.

**Comment by andrey-utkin** [comment]
Funnily, Github doesn't even allow to merge PR with a merge commit in the RNP repo, at least not by the button.

**Comment by ronaldtse** [comment]
Our convention is to rebase changes instead of merging them. 

Why not just use the hash issue number in the commit? What's wrong with GitHub picking up the GitHub issue numbers?

**Comment by andrey-utkin** [comment]
> What's wrong with GitHub picking up the GitHub issue numbers?

What Nickolay has pointed to: that the web page with this issue is getting longer each time I push rewritten history, which is distracting when you're trying to follow the discussion happening there.

**Comment by ronaldtse** [comment]
> > What's wrong with GitHub picking up the GitHub issue numbers?
> 
> What Nickolay has pointed to: that the web page with this issue is getting longer each time I push rewritten history, which is distracting when you're trying to follow the discussion happening there.

Ah I see. The rewritten commits being shown don't bother me that much. Perhaps my brain is now trained to ignore them...

**Comment by andrey-utkin** [comment]
https://github.com/rnpgp/rnp/pull/1875 merged. Closing.
