### ISSUE TITLE
FFI: add function to retrieve used backend and it's version.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1597]
## Description

Interface could be as following:
- `RNP_API const char *rnp_backend_string()`
- `RNP_API rnp_result_t rnp_backend_version(char **version)`

**Comment by antonsviridenko** [comment]
`RNP_API rnp_result_t rnp_backend_version(char **version)` - why this cannot be returned as a const string, like the previous one? Version string is not expected to be modified.

**Comment by ni4** [comment]
@antonsviridenko at least while linking to OpenSSL/Botan dynamically we should retrieve their versions at run time.
