### ISSUE TITLE
CLI: add option to export all public/secret keys

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1606]
## Description

Currently we may export keys based on search string/keyid/fingerprint. In some occasions it could be useful to export all keys (despite the fact that we may just copy keyring at the moment).
In GnuPG `-a` option is used to export all of the keys.

**Comment by antonsviridenko** [comment]
> In GnuPG -a option is used to export all of the keys.

Actually,

`-a` is a synonym for `--armor`
``` 
Create ASCII armored output.  The default is to create the binary OpenPGP format.
```
and all keys are exported by default if no search pattern is specified.

I think we need the same behavior in `rnpkeys`. Now it prints
```
No key specified.
```
if no search pattern was provided.
However, `man 1 rnpkeys` says
```
*--export-key* [*--userid*=_FILTER_] [_FILTER_]::
Export key(s). Only export keys that match _FILTER_ if _FILTER_ is given. +
```
i.e. missing search filter is supposed to be acceptable and should mean export all keys.

**Comment by ni4** [comment]
@antonsviridenko I don't think that it should work in this way, as user may accidentally export all of his keys if he forgets to type in filter. More correct would be to add some flags like `--all`, and fix the manual page.

**Comment by antonsviridenko** [comment]
But `gpg` works this way and it seems reasonable and expected default behavior.  Secret keys are not exported anyway unless `--secret` is explicitly passed, so no security issue here.

**Comment by ni4** [comment]
@antonsviridenko Not sure whether we should duplicate GnuPG's style here. @ronaldtse what's your opinion on this?

**Comment by antonsviridenko** [comment]
@ronaldtse can you comment?

**Comment by ronaldtse** [comment]
Sorry for the delay in replying. I think the GnuPG style is acceptable for now since many people are familiar with it.

The thing is I'm not sure what the alternative can be with filtering. Unless we are saying that we will list out the keys for explicit criteria?

**Comment by antonsviridenko** [comment]
> The thing is I'm not sure what the alternative can be with filtering. Unless we are saying that we will list out the keys for explicit criteria?

Empty filter matches all keys. Like this:
```
rnpkeys --export ''
```

But it is not mentioned in the documentation. Also it's not mentioned that regular expressions are used for filter syntax.

**Comment by ronaldtse** [comment]
1. Should we always ensure that a filter is provided?
2. We should update documentation

**Comment by antonsviridenko** [comment]
> Should we always ensure that a filter is provided?

It is the default behavior now, it prints `No key specified.` error message if no filter argument is passed, like I mentioned above. #2087 is supposed to change it and make the filter agument optional.
