### ISSUE TITLE
CLI: add to the rnp options --s2k-iterations and s2k-msec

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1608]
## Description

Currently these options are available only for the rnpkeys, however may be usable for rnp as well during symmetric encryption  - to make encryption stronger, make tests run faster, and so on.

**Comment by antonsviridenko** [comment]
@ni4 looks like configured values are used only in one single place in `rnpkeys' code
https://github.com/rnpgp/rnp/blob/master/src/rnpkeys/tui.cpp#L303

so probably rnp code should be updated to use configured values instead of defaults

**Comment by ni4** [comment]
@antonsviridenko I'm not sure whether I understand you correctly. S2K is used in 2 cases - to protect secret key (so it is used during key generation in the code you mentioned), and to protect encrypting key used by password-based encryption. For the later one please see function `rnp_op_encrypt_add_password()`.
