### ISSUE TITLE
CLI: add --keyfile option to the rnpkeys

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1611]
## Description

This option may be usable in the following scenarios:
- `rnpkeys --keyfile key.asc --list-keys` to list keys, stored in the file
- `rnpkeys --keyfile key.asc --generate-key` to store generated secret key in the file specified
- `rnpkeys --keyfile key.asc --export-key` to export subkey(s) or offline key
- `rnpkeys --keyfile key.asc --export-rev` to export key's revocation

**Comment by antonsviridenko** [comment]
> rnpkeys --keyfile key.asc --generate-key to store generated secret key in the file specified

Can we omit this scenario? `rnp` executable uses `--keyfile` as a source file only. In order to keep it consistent. Maybe we can add additional option for storing the generated key in non-default location, something like `--store-key` or maybe existing option `--output` can be used instead.

**Comment by antonsviridenko** [comment]
Should we assume the argument to the `--keyfile` to be a PGP file or a keystore with multiple possible formats?

**Comment by ni4** [comment]
@antonsviridenko 
> Can we omit this scenario? rnp executable uses --keyfile as a source file only. 

Agree, we could use some other option for this.

> Should we assume the argument to the --keyfile to be a PGP file or a keystore with multiple possible formats?

Consider it as file with OpenPGP transferable key, i.e. `RNP_KEYSTORE_GPG`.
