### ISSUE TITLE
How to get rid of setting a password(password cb) while generating keys

### ISSUE THREAD

**Issue by sariug** [rnpgp/rnp#1625]
Hello,

I am new to the library (and im def not a cryptography or something) so everything is a little bit mystery to me. A quick question is that, I do not want to set/read a password. Is it possible to get rid of that part while generating keys?

Thank you  best regards

**Comment by sariug** [comment]
I closed the issue as the answer was helpful enough! thanks! :) 

Sorry that I can't provide any more details.

A quick question though. I am failing to write the keys with armor.  Whats the way to write the keys with armor(and therefore ascii, rather than binary)? The example generates also binary.

**Comment by ni4** [comment]
> A quick question though. I am failing to write the keys with armor. Whats the way to write the keys with armor(and therefore ascii, rather than binary)? The example generates also binary.

You should just add `RNP_KEY_EXPORT_ARMORED` flag to the `rnp_key_export()` call.
