### ISSUE TITLE
LGTM alerts: Declaration hides parameter C++

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1650]
## Description
<img width="1231" alt="Screenshot 2021-10-14 at 10 29 36 PM" src="https://user-images.githubusercontent.com/11865/137338188-79bbc9e3-c62a-43f0-a2ee-52aa960acb1d.png">

<img width="1231" alt="Screenshot 2021-10-14 at 10 29 46 PM" src="https://user-images.githubusercontent.com/11865/137338216-7cec3ad0-0abe-4529-9419-a27481539115.png">

<img width="1228" alt="Screenshot 2021-10-14 at 10 29 53 PM" src="https://user-images.githubusercontent.com/11865/137338239-d62c7e22-b121-4706-bd48-55a4ab1a9214.png">

**Comment by ni4** [comment]
Fixed via #1652, so closing.
