### ISSUE TITLE
clang/GnuPG v2.3.0-beta983 issue (CentOS 8 workflow)

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#1669]
**Target:** CentOS 8
**Tests** (normal, beta, clang, clang++),  (sanitize, beta, clang, clang++)
**Module:** GnuPG v2.3.0-beta983
**Error:**
```
libcommon.a(libcommon_a-iobuf.o):(.bss+0x8): multiple definition of `iobuf_debug_mode'
t-iobuf.o:(.bss+0x0): first defined here
``` 
Other tests use GnuPG v2.2.24 whicj compiles without issues.

_Originally posted by @maxirmx in https://github.com/rnpgp/rnp/issues/1129#issuecomment-959545493_

**Comment by ni4** [comment]
@maxirmx Probably we should use later beta (983 was picked just because it was the latest at the time when workflow was created).
Maybe this commits is related: https://dev.gnupg.org/rG6aff8a132815a84bab69401c1e7de96ec549fbf2

**Comment by maxirmx** [comment]
If they do not support and/or test clang in their beta build it will be a real adventure to rely on it here

**Comment by ronaldtse** [comment]
@maxirmx only RNP needs to be built with clang. Test modules like gnupg are installed using https://github.com/rnpgp/gpg-build-scripts and we don't care how they are built in this current repository. Thanks.

**Comment by maxirmx** [comment]
I will enforce gnu toolchain in _ci/lib/cacheable_install_functions.inc.sh_ 
This will fix CentOS8/clang workflow

**Comment by ronaldtse** [comment]
Thanks @maxirmx !
