### ISSUE TITLE
Add OpenSSL tests for ubuntu, debian9, windows (and maybe centos7)

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1691]
Similar to centos8-ossl, we should add a modular BACKEND matrix value for these platforms.

**Comment by maxirmx** [comment]
Centos7 openssl tests  -- https://github.com/rnpgp/rnp/issues/1929 (or earlier)
Windows (native) openssl tests -- https://github.com/rnpgp/rnp/pull/2028
MacOS openssl tests -- https://github.com/rnpgp/rnp/pull/2057

**Comment by ronaldtse** [comment]
@maxirmx if this is done please help close it. Thanks!
