### ISSUE TITLE
Add tests for RNG

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1722]
From @antonsviridenko

Do we have some tests for RNG output? Looks like no. 

We can try to use "Dieharder test suite"
* https://webhome.phy.duke.edu/~rgb/General/dieharder.php

Or make some corner cases when /dev/urandom is not available or not functioning as expected on a specific platform.

_Originally posted by @antonsviridenko in https://github.com/rnpgp/rnp/issues/1721#issuecomment-996271787_

**Comment by ni4** [comment]
@ronaldtse Should we thorougly test RNG given that it is implemented in the backend? Maybe some simple checks, like whether it works at all/outputs different data for different instances would be okay?
cc @antonsviridenko

**Comment by antonsviridenko** [comment]
> Maybe some simple checks, like whether it works at all/outputs different data for different instances would be okay?

Yeah, as essentially rnp's RNG is a wrapper around either botan or openssl implementation of RNG, some simple tests should be enough, to make sure it is not broken by some configuration error. Dieharder test suite can be used as a reference.

**Comment by antonsviridenko** [comment]
I think it would be nice to add command option like `--random` to the `rnp` command line tool, to produce random numbers output. It will make testing easier using existing tools. GnuPG already has such option named `--gen-random`.
