### ISSUE TITLE
Please update includePath for "config.h" in file-utils.cpp

### ISSUE THREAD

**Issue by BeginArjun** [rnpgp/rnp#1787]
## Please update **includePath** for **"config.h"** in file-utils.cpp

In Line no-31, *"rnp/src/common/file-utils.cpp"*, source file for **"config.h"** cannot be opened.
![image](https://user-images.githubusercontent.com/92989288/160244840-64afb7d3-4ffd-4cca-b3b1-481e34a24a74.png)

**Comment by ni4** [comment]
Hi, did you use cmake to build files or just added source files to the project? `config.h` is generated from the `config.h.in` during the cmake invocation.
