### ISSUE TITLE
rnp.h file location not found

### ISSUE THREAD

**Issue by BeginArjun** [rnpgp/rnp#1788]
## \#include <rnp/rnp.h> file not found.
> On Running the file, **"COMPILATION FAILED"**, due to missing file.
The file I tried running was *"rnp/src/examples/sign.c"*. 
![image](https://user-images.githubusercontent.com/92989288/160245806-4356a775-e9e8-41c9-bb48-a5af4803f349.png)
But, it's not just limited to this particular file. Here are some of the files I found with the same problem.
![image](https://user-images.githubusercontent.com/92989288/160245947-60a4fece-84e9-4fad-b474-79df0c40f342.png)

## Expected Behavior
> The files should have been compiled without giving any **ERROR**.

## Actual Behavior

> **Compilation Error**

**Comment by ni4** [comment]
`<rnp/rnp.h>` should be added to the include path of your project.
