### ISSUE TITLE
Build error for tests in "windows-msys2 / CC clang; GnuPG stable"

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1790]
There is an error in "windows-msys2 / CC clang; GnuPG stable" that affected PR #1781.

```
-- Generating done
-- Build files have been written to: D:/a/_temp/msys64/home/runneradmin/local-builds/rnp-build
+ make_install
+ make -j2 install
[  1%] Building CXX object src/common/CMakeFiles/rnp-common.dir/str-utils.cpp.obj
[  1%] Building CXX object src/tests/googletest-build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj
D:/a/rnp/rnp/src/common/str-utils.cpp:30:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
1 error generated.
In file included from D:/a/_temp/msys64/home/runneradmin/googletest-download/googletest-src/googletest/src/gtest-all.cc:38:
D:/a/_temp/msys64/home/runneradmin/googletest-download/googletest-src/googletest/include/gtest/gtest.h:55:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^~~~~~~~~
make[2]: *** [src/common/CMakeFiles/rnp-common.dir/build.make:76: src/common/CMakeFiles/rnp-common.dir/str-utils.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:1166: src/common/CMakeFiles/rnp-common.dir/all] Error 2
```

This error is only present on this particular configuration for some reason. 

We need to fix this.

_Originally posted by @ronaldtse in https://github.com/rnpgp/rnp/issues/1781#issuecomment-1081272530_

**Comment by ronaldtse** [comment]
@maxirmx since you are the Make expert, would you have time to check on this? Thanks!

**Comment by maxirmx** [comment]
Thank you, @ronaldtse )
It cannot find clang c++ include files which means that either 
[mingw-w64-x86_64-libc++](https://packages.msys2.org/package/mingw-w64-x86_64-libc++?repo=mingw64) is not installed or some environment variable is not properly set

**Comment by ni4** [comment]
@ronaldtse @maxirmx Thanks for filing this and participating in resolution of this issues. I tried to nail it down via the additional logging in #1789 but didn't succeed so far.

**Comment by maxirmx** [comment]
@ni4 @ronaldtse 
I fixed it. Pls give me some more time to finalize the solution

**Comment by ronaldtse** [comment]
Thank you @maxirmx ! I've added some minor comments in #1794, once those are resolved we should be able to merge

**Comment by ni4** [comment]
@maxirmx  Thanks for the explanation!
