### ISSUE TITLE
FFI: add API function/flag to do raw encryption of the input.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1795]
## Description

Currently RNP during encryption creates wrapping OpenPGP literal data packet/compressed data packet for the input.
However, in some scenarios (see https://bugzilla.mozilla.org/show_bug.cgi?id=1688863) it could be desirable to treat the input data as already wrapped.
It could be done via some function like `rnp_op_encrypt_set_flags(rnp_op_encrypt_t op, uint32_t flags)`.

**Comment by ronaldtse** [comment]
We will prioritise this functionality for the Thunderbird issue quoted (@kaie).
