### ISSUE TITLE
output for "rnp --decrypt" does not behave as documented

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1805]
rnp(1) says about decryption:

```
          --output
               Output, if not overridden with this option, will be written to
               the file with stripped .pgp extension or stdout. If INPUT_FILE
               does not end with the .pgp extension, then output file name
               will be asked via stdin/tty.
```

But when I `rnp --decrypt msg` using rnp 0.16.0, it automatically creates a file named `msg.out`.

**Comment by ni4** [comment]
Hmm, do you use this exact file naming/commands? I tried to reproduce it `rnp --decrypt msg`, where `msg` is ecrypted file name, and got result to the stdout.

**Comment by dkg** [comment]
apologies, i don't know where the `msg.out` came from.  when i re-run my tests after getting a night of sleep, i agree with you that it is being sent to stdout.

This still doesn't match the documented behavior, though.

> If INPUT_FILE does not end with the .pgp extension, then output file name will be asked via stdin/tty.

fwiw, i prefer emitting to stdout, so perhaps the best fix here is just to remove the sentence quoted above.

**Comment by ni4** [comment]
@dkg thanks for the clarification, finally get to it. We decided to fix CLI (and improve man page) to automatically strip known extensions. You are welcome to share your opinion on the changes.
