### ISSUE TITLE
`rnp_decrypt` semantics: should never fail based on signatures

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#1822]
The `rnp_decrypt` function documentation makes no claims about signature verification.  Any signatures encountered should be safely ignored.

However, when it is run against [`seipd1-sig23-sig4.pgp`](https://gitlab.com/openpgp-wg/unknown-signature-versions/-/blob/main/seipd1-sig23-sig4.pgp) it returns `RNP_ERROR_SIGNATURE_INVALID`.  And when it is run against [`seipd1-sig23.pgp`](https://gitlab.com/openpgp-wg/unknown-signature-versions/-/blob/main/seipd1-sig23.pgp) it produces `RNP_ERROR_BAD_PARAMETERS`.

`rnp_decrypt` should be able to safely discard any signatures it does not recognize.

This is related to #1820, in that they both deal with unknown signature packet versions.

**Comment by ni4** [comment]
Fixed via https://github.com/rnpgp/rnp/pull/1896 with the following output (with 0 return code):
```
$ rnp --homedir .rnp --decrypt 1.asc
[parse() .../rnp/src/librepgp/stream-packet.cpp:1211] wrong packet version
[parse() .../rnp/src/librepgp/stream-sig.cpp:1330] unknown signature version: 23
[signed_read_single_signature() .../rnp/src/librepgp/stream-parse.cpp:981] failed to parse signature
[signed_src_finish() .../rnp/src/librepgp/stream-parse.cpp:1062] warning: unexpected data on the stream end
UNKNOWN signature
Signature verification failure: 1 unknown signature
$ echo $?
0
```
