### ISSUE TITLE
CI failures on release/0.x branch as of v0.16.0

### ISSUE THREAD

**Issue by andrey-utkin** [rnpgp/rnp#1872]
## Description

The configured CI jobs (Github Actions) fail in many ways on 0.16.0 release itself, which makes it difficult to build a next patch release on top of it.

## Steps to Reproduce

1. Create a branch based on v0.16.0 git tag (or release/0.x branch) and add a trivial cosmetic change to the codebase, e.g. a no-op statement to src/lib/rnp.cpp
2. push the branch
3. create a draft pull request with release/0.x branch as a base

## Expected Behavior

All CI checks pass

## Actual Behavior

Many CI checks fail. This is my PR demonstrating the issue: https://github.com/rnpgp/rnp/pull/1871
> 27 failing, 22 successful, 1 skipped, and 1 neutral checks

https://github.com/rnpgp/rnp/runs/7252596896?check_suite_focus=true
> Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist

Many runs have this ruby-rnp test suite error:

`Failure/Error: expect(@json["expiration"]).to be 63072000`

Windows:
> could not find any instance of Visual Studio.

> D:/a/rnp/rnp/src/common/str-utils.cpp:30:10: fatal error: 'cstddef' file not found

"build" (freebsd?)
> pkg: No packages available to install matching 'ruby26' have been found in the repositories

**Comment by andrey-utkin** [comment]
Nickolay said there are fixes on master which should be cherry picked.
https://github.com/rnpgp/rnp/pull/1871#issuecomment-1180251635

**Comment by ni4** [comment]
This is something that would always happen as time flies: expiring keys, updated CI images and runners, changed timestamps and so on. So I don't see a cure from such failures. If you don't have any further questions - feel free to close it as not planned.

**Comment by andrey-utkin** [comment]
There's no cure, but scheduled runs help with discovering it earlier ;)
I am going to use this ticket to denote the prerequisite work to backporting of the #1859 patches onto the release branch.

**Comment by andrey-utkin** [comment]
The fix comes in three pieces.
1. The minor-stable-release branch (`release/0.x`?) should take three backport commits. https://github.com/rnpgp/rnp/pull/1874
2. The master branch of RNP repo should take the increment of version.txt https://github.com/rnpgp/rnp/pull/1873
3. ruby-rnp repo should change to distinguish master from the stable branch correctly: https://github.com/rnpgp/ruby-rnp/pull/81

**Comment by ni4** [comment]
Closing this as it was already resolved during the v0.16.1 release.
