### ISSUE TITLE
test_rnpcfg_get_expiration flaky

### ISSUE THREAD

**Issue by andrey-utkin** [rnpgp/rnp#1876]
## Description

rnp_tests.test_rnpcfg_get_expiration sometimes fails in CI for reasons unrelated to the particular pull request.
This looks like the test itself is unreliable.

## Steps to Reproduce

This happens from time to time in CI, not consistently.
Re-run CI repeatedly to trigger?

## Expected Behavior

The test always passes or is excluded/dropped.

## Actual Behavior

```
[ RUN      ] rnp_tests.test_rnpcfg_get_expiration
/tmp/cirrus-ci-build/src/tests/utils-rnpcfg.cpp:139: Failure
Expected equality of these values:
  (raw_expiry)
    Which is: 567238
  (rawtime - basetime)
    Which is: 567239
[  FAILED  ] rnp_tests.test_rnpcfg_get_expiration (93 ms)
```
https://github.com/rnpgp/rnp/pull/1870/checks?check_run_id=7299435924

**Comment by antonsviridenko** [comment]
Fixed in #2089
