### ISSUE TITLE
Combine CI workflows of all CentOS/Fedora/RHEL into one

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1891]
## Description

Only one CI workflow is really needed.

e.g. https://github.com/ansible/pylibssh/blob/devel/.github/workflows/build-test-n-publish.yml#L706-L720

**Comment by maxirmx** [comment]
CentOS/Fedora squashed workflow sample: https://github.com/rnpgp/sexp/blob/main/.github/workflows/build-and-test-rh.yml
Debian squashed workflow sample: https://github.com/rnpgp/sexp/blob/main/.github/workflows/build-and-test-deb.yml

Debian workflow also has cmake installation from binary distribution and reduces run time dramatically
