### ISSUE TITLE
Cannot open source file rnp_export.h .

### ISSUE THREAD

**Issue by Lewi97** [rnpgp/rnp#1898]
## Description

I have been trying to use the C API to support OpenPGP encryption within my own project, but while trying to compile one of the examples i keep getting stuck on the following include error: 
![image](https://user-images.githubusercontent.com/86553904/188641273-08a35e2f-86a9-4d28-a1c6-d1622083833d.png)

This file "rnp_export.h" has been driving me on a witchhunt for the past couple hours as i can't find it anywhere within the repo or on the internet. I hope this is an actual issue and im not just inconveniencing someone because i overlooked something.

This has all been done in Microsoft Visual Studio Community 2022.
The example in question: ``generate.c``

## Steps to Reproduce

1. Clone the repo
2. Add the ``include`` folder to the include path of my project
3. try to include ``<rpn/rpn.h>``

## Expected Behavior

For the example to compile without include errors.

## Actual Behavior

![image](https://user-images.githubusercontent.com/86553904/188641273-08a35e2f-86a9-4d28-a1c6-d1622083833d.png)

**Comment by ni4** [comment]
@Lewi97 this file is generated by cmake during compilation/installation, and contains system-dependent defines, used to export symbols from the library. 
Please see `windows-msvc.yml` file under the `.github/workflows/` for the hint on how to build lib for Windows.

**Comment by Lewi97** [comment]
@ni4 Thank you, that solved it.
