### ISSUE TITLE
Can't find entry point of certain procedures in .dll error when running any of the examples

### ISSUE THREAD

**Issue by Lewi97** [rnpgp/rnp#1899]
## Description

Building from source using MSYS resulted in the binaries for the examples producing dll errors stating that they are unable to find the entry point for two functions, more info down below.
I followed the steps from the MSYS guide ``https://github.com/rnpgp/rnp/blob/master/docs/installation.adoc#using-msysmingw`` thrice, using the CLang and MingW consoles, the 64 bit versions just to be sure with administrator privileges.

Both also produced the following error in their console output after running the final step ``make && make install``:

```[ 98%] Building CXX object src/tests/CMakeFiles/rnp_tests.dir/fuzz_dump.cpp.obj
[ 99%] Building CXX object src/tests/CMakeFiles/rnp_tests.dir/fuzz_verify_detached.cpp.obj
[ 99%] Building CXX object src/tests/CMakeFiles/rnp_tests.dir/fuzz_verify.cpp.obj
[100%] Linking CXX executable rnp_tests.exe
CMake Error at D:/programs/msys/mingw64/share/cmake/Modules/GoogleTestAddTests.cmake:112 (message):
  Error running test executable.

    Path: 'C:/libs/rnp-build-c/src/tests/rnp_tests.exe'
    Result: Exit code 0xc0000135



    Output:


Call Stack (most recent call first):
  D:/programs/msys/mingw64/share/cmake/Modules/GoogleTestAddTests.cmake:225 (gtest_discover_tests_impl)


make[2]: *** [src/tests/CMakeFiles/rnp_tests.dir/build.make:1067: src/tests/rnp_tests.exe] Error 1
make[2]: *** Deleting file 'src/tests/rnp_tests.exe'
make[1]: *** [CMakeFiles/Makefile2:1310: src/tests/CMakeFiles/rnp_tests.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

## Steps to Reproduce

1. Clone the repo
2. Create a dir outside the source directory
3. Follow https://github.com/rnpgp/rnp/blob/master/docs/installation.adoc#using-msysmingw 
4. Run any of the binaries in the src/example folder

## Expected Behavior

The examples should run without errors.

## Actual Behavior

The following errors:
![image](https://user-images.githubusercontent.com/86553904/188929432-4c76518c-182d-465f-8c86-2350d0b0cbe2.png)
![image](https://user-images.githubusercontent.com/86553904/188943277-37f1b9ab-5454-4856-b280-109681aa9c5d.png)
It is unable to find the following functions in librpn.dll and libbotan-2.dll.

I hope im bringing an actual issue to light and not proof of me overlooking something important.

**Comment by ni4** [comment]
@Lewi97 Just to make sure - are `librnp.dll` and `libbotan-2.dll` on `$PATH`? You may also check our GHA workflows/CI scripts for the details how it is built.

**Comment by Lewi97** [comment]
@ni4 Interesting, adding them to $PATH and running the binaries in the MingW terminal resulted in expected behaviour. However running them by just double clicking the .exe reintroduced the errors.

**Comment by ni4** [comment]
@Lewi97 That's actually expected, as Windows doesn't know where to look for dll's as they are stored in build directories, not the same as executable.

**Comment by Lewi97** [comment]
@ni4 Thanks for the clarification, then it seems like it did build everything correctly!
