### ISSUE TITLE
ENABLE_IDEA not working

### ISSUE THREAD

**Issue by jfx2006** [rnpgp/rnp#1901]
## Description

In 0.16.1, IDEA support does not get enabled despite Botan supporting it

## Steps to Reproduce

1. Run `cmake -S rnp-0.16.1 -B build`
2. Build: `cd build && make`
3. Execute the built "rnpkeys" binary without any arguments: `./src/rnpkeys/rnpkeys`

## Expected Behavior

The "Encryption" line should include "IDEA" in its list

## Actual Behavior

IDEA does not appear in the "Encryption" line:
`Encryption:  TRIPLEDES, CAST5, BLOWFISH, AES128, AES192, AES256, TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256, SM4`

Adding `#cmakedefine ENABLE_IDEA` to be `src/lib/config.h.in` fixes the issue.

**Comment by ni4** [comment]
@jfx2006 Wow, how could we (and our tests) miss that! Thanks for reporting, we'll work on fixing this.
