### ISSUE TITLE
CI: Possible inconsistency for RNP_INSTALL

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#1907]
## Description

Not sure whether this is an issue, but `env-common.inc.sh` and `ci/gha/setup-env.inc.sh` both define `RNP_INSTALL` variable.
First one sets it to `$HOME/local-installs/rnp-install`, while second to the `${GITHUB_WORKSPACE}/rnp-install`.

**Comment by maxirmx** [comment]
Closing it since new CI scripts do not use either ```env-common.inc.sh``` or ```ci/gha/setup-env.inc.sh```
