### ISSUE TITLE
Refactor CI: Centos/Fedora workflow

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#1929]
Target flow:
1. build / run tests  ( for different flavours, OS versions and architectures )
2. build a SRPM, install it and test ( for different flavours, versions and architectures ) 
    (publish SRPM as an artifact)
4. build RPMs  ( for different flavours, versions and architectures )  and then test them 
    (publish RPMs as artifacts)

**Comment by ronaldtse** [comment]
This is correct. Thank you @maxirmx !

**Comment by maxirmx** [comment]
CentOS/Fedora squashed workflow sample: https://github.com/rnpgp/sexp/blob/main/.github/workflows/build-and-test-rh.yml

**Comment by ronaldtse** [comment]
This issue depends on:
* [ ] #1891 
* [ ] #1962
