### ISSUE TITLE
Change default branch from `master` to `main`

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1937]
## Description

It is now customary to use `main` instead of `master` as the default branch.

**Comment by ronaldtse** [comment]
@ribose-jeffreylau @ni4 @antonsviridenko any precautions we should take before the change?

**Comment by ni4** [comment]
All dependencies (like oss-fuzz, brewfile, whatever else?) which were sticked to default master naming could be affected. Probably we should re-check and build a list of things which should be updated.

**Comment by ronaldtse** [comment]
The downstream packaging repos need to be updated, but I believe they use the latest tag versions:

* https://github.com/rnpgp/homebrew-rnp
* https://github.com/rnpgp/chocolatey-rnp
* https://github.com/rnpgp/gentoo-rnp
* https://github.com/rnpgp/rnp-snap

**Comment by maxirmx** [comment]
- [ ] https://github.com/rnpgp/rnp/oss-fuzz ----- uses default branch
- [ ] https://github.com/rnpgp/rnp/py-rnp ----- will be ok after https://github.com/rnpgp/py-rnp/pull/8	
- [ ] https://github.com/rnpgp/rnp/ruby-rnp ----- will be ok after https://github.com/rnpgp/ruby-rnp/pull/89
- [ ] https://github.com/rnpgp/rnp/php-rnp ----- will be ok after https://github.com/rnpgp/php-rnp/pull/10
- [ ] https://github.com/rnpgp/rnp/chocolatey-rnp ----- uses hardcoded 0.13.1 release tag, not branch name
- [ ] https://github.com/rnpgp/rnp/gentoo-rnp ----- uses release tag, not branch name
- [ ] https://github.com/rnpgp/rnp/rnp-objective-c ----- has 0.15.2 dylib checked in
- [ ] https://github.com/rnpgp/rnp/homebrew-rnp ----- uses hardcoded 0.15.2 release tag, bot branch name
- [ ] https://github.com/rnpgp/rnp/snap-rnp ----- uses the last commited tag, not branch
- [ ] https://github.com/rnpgp/rnp/rust-rnp ----- empty
- [ ] https://github.com/rnpgp/rnp/go-rnp ----- empty
