### ISSUE TITLE
Windows console build with CMake fail due to build tests

### ISSUE THREAD

**Issue by flydev-fr** [rnpgp/rnp#1938]
## Description

Following github documentation to run a console build with CMake on Windows 64bits fail due to `build tests`

## Steps to Reproduce

1. clone the repo
2. install vcpkg deps
3. run `cmake -B . -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake -DCMAKE_BUILD_TYPE=Release .`

## Expected Behavior

Build without error.

## Actual Behavior

> -- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- WIN_LIBRARY_DIR: 
-- Configuring done
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
SHLWAPI_LIBRARY
    linked by target "rnp_tests" in directory C:/Users/foo/dev/lib/rnp-build/src/tests      
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

## Observations to build it successfully

Commenting lines [CMakeLists.txt#L80](https://github.com/rnpgp/rnp/blob/master/CMakeLists.txt#L80) and [CMakeLists.txt#L193](https://github.com/rnpgp/rnp/blob/master/CMakeLists.txt#L193), make rnp building successfully.

**Comment by ni4** [comment]
To turn off tests building you should also add ` -DBUILD_TESTING=off` option to CMake call. And, definitely, building tests would fail if `CTest` is not found.
We would update documentation, as this option is specified for Linux builds.
