### ISSUE TITLE
Combine CI workflows of all Debian into one

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#1963]
Similar to #1891, these platforms are highly similar such that a single CI workflow should work.

**Comment by maxirmx** [comment]
While Debian and Ubuntu are similar, the structure of GHA workflow is different for them.
Ubuntu is executed in GHA runner, Debian requires extra container. 
I do not think it is feasible to combine Ubuntu and Debian together.

**Comment by ronaldtse** [comment]
> I do not think it is feasible to combine Ubuntu and Debian together.
Yes that's fine. I nearly forgot GHA provides Ubuntu by default while Debian is through a Docker image.
