### ISSUE TITLE
CI: Botan library handling/versioning  in CI scripts

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#2007]
Now for CentOS/Fedora CI scripts do the following

- Install botan2, botan2-devel packages  (unconditionally) [from https://github.com/riboseinc/rpm-spec-botan2, version **2.16.1**]
- Build botan from source and link against it (unconditionally) [**2.17.3** on CentOS 7/**2.18.2** on other platforms]

In all CMake scripts we have ```find_package(Botan2``` **2.14.0** ```REQUIRED)``` which is inconsistent with CI shell scripts

So,  two questions
- what is the minimal Botan version we support (want to support) ?
- do we want to use Botan rpm from https://github.com/riboseinc/rpm-spec-botan2 ?

**Comment by maxirmx** [comment]
(for CentOS/Fedora only)
We have CI tests that are run against 2.17.3/2.18.2 (locally built)
We have packaging that is done against 2.16.1/2.19.1/2.19.3
We have packaging test that is done with 2.14.0+ requirement

It may be good good enough but it does not look robust enough. 

We shall test and package against the same versions

**Option 1**
```
CentOS 7,8    against 2.16.1   from ribose repo          [and downgrade version in tests]
CentOS 9      against 2.19.3   from EPEL9               [and upgrade version in tests]
Fedora35      against 2.19.1   from Fedora packages     [and upgrade version in tests]
Fedora36      against 2.19.1   from Fedora packages     [and upgrade version in tests]
```

**Option 2**
```
CentOS 7,8    against 2.17.3   from ribose repo         [and add it to ribose repo]
CentOS 9      against 2.18.2   from ribose repo         [and add it to ribose repo]
Fedora35      against 2.18.2   from ribose repo                               
Fedora36      against 2.18.2   from ribose repo                               
```
(more options are possible)

For me _Option 1_  is better, however, current implemenation looks like outdated _Option 2_

So the question is wheather we want to  change the approach towards _Option 1_ or have _Option 2_ fixed

**Comment by maxirmx** [comment]
UPD  
_We shall test and package against the same versions_  is incorrect

**We shall package against the versions we have tested**

**Comment by ni4** [comment]
I would vote for Option 1, as this would be the case which is used by RNP users.

**Comment by maxirmx** [comment]
ref #1908

**Comment by ronaldtse** [comment]
I agree with Option 1.  Ideally we don't want to maintain a Botan package unless absolutely necessary.
