### ISSUE TITLE
Change sexp packaging in unknown but convinient way

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#2015]
Per discussion at https://github.com/rnpgp/rnp/pull/2004

**Option 1**
1. Keep sexp git project
2. Include sexp source files into rnp source tree as git submodule
3. build sexp library using CMake add_subdirectory feature 
4. distributes sexp source within rnp source package
5. distribute sexp library within rnp binary package (as it is implemented already
 
**Option 2**
1. Keep sexp git project
2. Copy sexp source files into rnp source tree
3. Add special workflow that will be triggered on sexp release and 
   - create branch in rnp project (like here https://github.com/marketplace/actions/push-directory-to-another-repository)
   - copy updated sexp sources into newly created branch
   - create pull request for new branch (https://github.com/marketplace/actions/create-pull-request)
4. Build sexp library using CMake add_subdirectory feature 
5. Distributes sexp source within rnp source package
6. Distribute sexp library within rnp binary package (as it is implemented already

@ronaldtse @ni4 @antonsviridenko

**Comment by ronaldtse** [comment]
It seems that Option 1 is the more straightforward way here. Option 2 step 2 is likely not what we want because it will can create a maintenance burden.

**Comment by ni4** [comment]
I'd vote for Option 1, however not sure about the submodule usage, as per this discussion: https://news.ycombinator.com/item?id=31792303

Given that SExp code should not be updated too often, why not to just copy sources, and do updating PRs once SExp code is updated? And, regarding the 1.5 - why should we distribute sexp library with RNP, given that all code from it is compiled into the RNP lib and doesn't expose anything to the outer space?

**Comment by ronaldtse** [comment]
> why not to just copy sources, and do updating PRs once SExp code is updated

Personally I think the "copy" step can already be achieved by using the submodule. When SExp code is updated (to a new release tag), we just need to make a PR that switches the submodule tag to the new release tag.

> And, regarding the 1.5 - why should we distribute sexp library with RNP, given that all code from it is compiled into the RNP lib and doesn't expose anything to the outer space?

I agree that we should compile SExp into RNP lib without exposing it, as there is no need to?

**Comment by maxirmx** [comment]
- git submodule automates copy with consideration of moves  and deletes

- If rnp is used as shared library sexp is linked into it
   If rnp is used as static library it references sexp as another library and it needs to be provided.  This is true about other components as well (libz, botan, json-c) and BTW it is implemented with issue https://github.com/rnpgp/rnp/issues/2012

**Comment by ni4** [comment]
Ok, agree with Git submodule. Anyway, if that would cause any issues we may change that later.
Regarding the SExp static lib - still don't get why not to include sources into the RNP project and compile it in? libz/botan/json-c work in that way as they may be required by multiple applications/libraries, while SExp would be required only by RNP?

**Comment by maxirmx** [comment]
> regarding the SExp static lib - still don't get why not to include sources into the RNP project and compile it in?

I created a standalone reusable library because @ronaldtse suggested to create a standalone reusable library and you agreed
https://github.com/rnpgp/rnp/issues/1724#issuecomment-1239334424

If we do not want to have a standalone reusable library we can include sources into the RNP project

**Comment by ronaldtse** [comment]
> suggested to create a standalone reusable library  

Yes it would be better to keep it maintained and tested independently.

> If rnp is used as static library it references sexp as another library and it needs to be provided

I'm fine with handling sexp in the same way as json-c .

**Comment by ni4** [comment]
Okay, let's treat it as a separate library (like json-c, etc), not the part of RNP sources, extracted for better flexibility.

**Comment by dkg** [comment]
@ronaldtse wrote:

> I'm fine with handling sexp in the same way as json-c.

fwiw, as of rnp 0.17.0, sexp is *not* handled the same way as json-c is handled.  If you want it as a separate library, then it needs to be a shared library, as noted in https://github.com/rnpgp/sexp/issues/32 .  In that case, it doesn't need to be a git submodule at all.

**Comment by andreasstieger** [comment]
The openSUSE package patches sexp to be a proper shared library, and rnp to use it.
