### ISSUE TITLE
Something go wrong when I run the generate.c file

### ISSUE THREAD

**Issue by qwqOscar** [rnpgp/rnp#2027]
## Description

Describe the problem here.
when I get the environment down, and I run the example file generate.c, and I got a error "failed to generate eddsa key", when I got to debug it, I find more info like:
[Hash_Botan() D:\RNP\rnp\src\lib\crypto\hash.cpp:58] Error creating hash object for 'SHA-256'
[add_uid_cert() D:\RNP\rnp\src\lib\pgp-key.cpp:2404] Failed to certify: rnp_exception
[pgp_generate_primary_key() D:\RNP\rnp\src\lib\generate-key.cpp:354] Failure: rnp_exception
failed to generate eddsa key
Is there anything wrong?
I guess the reason is something wrong between the default libs of VS2019 and vcpkg libs.

## Steps to Reproduce
 
1. get the environment down using vcpkg as the rnp official doc says
2. run the example
3. 

## Expected Behavior

What is the expected behavior?
generate the the new EDDSA and RSA key

## Actual Behavior
go wrong and I can't find any solution on the internet.

What behavior did you observe instead?

**Comment by ni4** [comment]
@qwqOscar Thanks for raising this issue. Could you please specify which Botan version you are using?

**Comment by qwqOscar** [comment]
Hi！这里是Oscar！如果收到这条信息表明你已成功发送，我会尽快阅读or回复你的邮件。你也可以私戳来提醒我看邮件。祝好！

**Comment by qwqOscar** [comment]
> @qwqOscar Thanks for raising this issue. Could you please specify which Botan version you are using?

I have solved the problem by setting VS 2019 to release mode. I haven't learned the difference between the debug mode and release mode, but it seems to influence the Botan lib. By the way, my Botan version is 2.19.3.
