### ISSUE TITLE
Update codecov branch setting to main

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#2047]
Codecov: it is not yet recognizing the `main` branch so we can't change it yet.

https://app.codecov.io/gh/rnpgp/rnp/settings

_Originally posted by @ronaldtse in https://github.com/rnpgp/rnp/issues/2046#issuecomment-1504843766_

**Comment by ronaldtse** [comment]
Still not updated. Maybe it needs a commit to main to trigger.

**Comment by maxirmx** [comment]
I have updated codecov settings
Now changing the badge

**Comment by ronaldtse** [comment]
Confirm changed. Thanks!
