### ISSUE TITLE
static_assert failed when building debug version with clang-cl

### ISSUE THREAD

**Issue by ValeV008** [rnpgp/rnp#2056]
## Description

System: Windows 10 64 bit, cmake, clang-cl, debug build.

When cmake building the debug version of the library, it stops with error 'static_assert failed due to requirement 'std::is_integral<std::_Container_proxy>::value' "T must be integral type"'.

## Steps to Reproduce

1. Clone latest rnp main branch and update submodules.
2. cmake ..\rnp_release -D CMAKE_BUILD_TYPE=Debug -D CMAKE_INSTALL_PREFIX="INSTALL" -D BUILD_SHARED_LIBS=on -D BUILD_TESTING=off -D CRYPTO_BACKEND="openssl" -D ENABLE_COVERAGE=off -D DIRENT_INCLUDE_DIR="C:\Users\C081745\OneDrive\Desktop\rnp_release\include\dirent" -D GETOPT_INCLUDE_DIR="C:\Users\C081745\OneDrive\Desktop\rnp_release\include\getopt" -D GETOPT_LIBRARY="C:\Users\C081745\OneDrive\Desktop\rnp_release\include\getopt\getoptd.lib" -D CMAKE_PREFIX_PATH="C:\Users\C081745\OneDrive\Desktop\tplib64_clang_x64\openssl;C:\Users\C081745\OneDrive\Desktop\tplib64_clang_x64\zlib;C:\Users\C081745\OneDrive\Desktop\bzip2;C:\Users\C081745\OneDrive\Desktop\json-c_all\build_debug\INSTALL" -G "Visual Studio 16 2019" -T ClangCL -A x64
3. cmake --build . --config Debug

## Expected Behavior

To build successfully.

## Actual Behavior

Building stop with:
`C:\Users\C081745\OneDrive\Desktop\rnp_release\src\lib\crypto/mem.h(47,5): error : static_assert failed due to requirement 'std::is_integral<std::_Container_proxy>::value' "T must be integral type" [C:
\Users\C081745\OneDrive\Desktop\rnp_build_debug\src\lib\librnp-obj.vcxproj]`

And another error:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.28.29910\include\vector(682,27): error : no matching conversion for static_cast from 'std::vector<unsigned char, rnp::ossl_alloc
ator<unsigned char>>::_Alty' (aka 'ossl_allocator<unsigned char>') to '_Rebind_alloc_t<std::vector<unsigned char, rnp::ossl_allocator<unsigned char>>::_Alty, std::_Container_proxy>' (aka 'ossl_allocator<std::_C
ontainer_proxy>') [C:\Users\C081745\OneDrive\Desktop\rnp_build_debug\src\lib\librnp-obj.vcxproj]`

[log.txt](https://github.com/rnpgp/rnp/files/11272088/log.txt)

**Comment by maxirmx** [comment]
Thank you, @ValeV008 
I think these issues are loosely related to rnp
If you have (1) clang  (2) on Windows, i.e.: clang-cl (3) in DEBUG  then it does not consider uint8_t to be an integral type

It would be nice to create a minimal example to see if there is any rnp impact and send it to the clang team, but I'm not sure when I can do that.

**Comment by ValeV008** [comment]
Thank you.

I changed the compiler to msvc (still trying to build debug), but got same error.

`C:\Users\C081745\OneDrive\Desktop\rnp_release\src\lib\crypto\mem.h(47,40): error C2338: T must be integral type [C:\Users\C081745\OneDrive\Desktop\rnp_msvc_build_debug\src\lib\librnp-obj.vcxproj]`

**Comment by maxirmx** [comment]
Hi, @ValeV008 

You are right -- clang-cl uses standart library from Visual Studio. So this error does not depend on compiler itself.

Here follows the minimal example, that fails with this error:
```
#include <type_traits>
#include <vector>

template <typename T> class ossl_allocator {
  public:
    static_assert(std::is_integral<T>::value, "T must be integral type");

    typedef T           value_type;
    typedef std::size_t size_type;

    ossl_allocator() noexcept = default;
    ossl_allocator(const ossl_allocator &) noexcept = default;
    ossl_allocator &operator=(const ossl_allocator &) noexcept = default;
    ~ossl_allocator() noexcept = default;

    template <typename U> ossl_allocator(const ossl_allocator<U> &) noexcept
    {
    }

    T *
    allocate(std::size_t n)
    {
        if (!n) {
            return nullptr;
        }

        /* fallback to std::alloc if failed */
        T *ptr = static_cast<T *>(std::calloc(n, sizeof(T)));
        if (!ptr)
            throw std::bad_alloc();
        return ptr;
    }

    void
    deallocate(T *p, std::size_t n)
    {
        if (!p) {
            return;
        }
        std::free(p);
    }
};

template <typename T> using secure_vector = std::vector<T, ossl_allocator<T> >;

int main(int, char**)
{
   static_assert(std::is_integral<uint8_t>::value, "T must be integral type");
   secure_vector<uint8_t> uint8_secure_vector;
   return 0;
}
```

A moving assert a level up fixes the issue
```
#include <type_traits>
#include <vector>

template <typename T> class ossl_allocator {
  public:
    typedef T           value_type;
    typedef std::size_t size_type;

    ossl_allocator() noexcept = default;
    ossl_allocator(const ossl_allocator &) noexcept = default;
    ossl_allocator &operator=(const ossl_allocator &) noexcept = default;
    ~ossl_allocator() noexcept = default;

    template <typename U> ossl_allocator(const ossl_allocator<U> &) noexcept
    {
    }

    T *
    allocate(std::size_t n)
    {
        if (!n) {
            return nullptr;
        }

        /* fallback to std::alloc if failed */
        T *ptr = static_cast<T *>(std::calloc(n, sizeof(T)));
        if (!ptr)
            throw std::bad_alloc();
        return ptr;
    }

    void
    deallocate(T *p, std::size_t n)
    {
        if (!p) {
            return;
        }
        std::free(p);
    }
};

template <typename T> class secure_vector : public std::vector<T, ossl_allocator<T> > {
    static_assert(std::is_integral<T>::value, "T must be integral type");
};

int main(int, char**)
{
   static_assert(std::is_integral<uint8_t>::value, "T must be integral type");
   secure_vector<uint8_t> uint8_secure_vector;
   return 0;
}
```
However, it still looks like Microsoft issue  for me
