### ISSUE TITLE
Debian 9 “Stretch” EOL

### ISSUE THREAD

**Issue by maxirmx** [rnpgp/rnp#2061]
On the 30 June 2022, Debian 9 “Stretch” went End of Life (EOL).
It looks like  ```http://deb.debian.org/debian stretch```  is not available anymore

I suggest to replace it with Debian 10 “Buster” in CI

https://wiki.debian.org/LTS

**Comment by ronaldtse** [comment]
Agree. Any thoughts @ni4 @antonsviridenko ?

**Comment by antonsviridenko** [comment]
Yes, let's remove EOL-ed distros.
