### ISSUE TITLE
0.17.0: `test_set_expire` fails on mipsel and mips64el

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#2118]
on the debian build daemon network, [mips64el](https://buildd.debian.org/status/fetch.php?pkg=rnp&arch=mips64el&ver=0.17.0-2&stamp=1692128274&raw=0) and [mipsel](https://buildd.debian.org/status/fetch.php?pkg=rnp&arch=mipsel&ver=0.17.0-2&stamp=1692132673&raw=0) builds both fail the `test_set_expire` test on rnp 0.17.0.

on both platforms, we see the same error:

```
======================================================================
FAIL: test_set_expire (__main__.Keystore.test_set_expire)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/src/tests/cli_tests.py", line 2003, in test_set_expire
    self.assertRegex(out, r'(?s)^.*\[EXPIRES .*')
AssertionError: Regex didn't match: '(?s)^.*\\[EXPIRES .*' not found in '\nsec   2048/RSA 14117ec7b8576dfb 2023-08-15 [SC] [EXPIRED 2023-08-15]\n      369d4f087c5905904eddc4fc14117ec7b8576dfb\nuid           primary_with_empty_password@rnp\n'

----------------------------------------------------------------------
```

It seems to build fine on [the other platforms in debian](https://buildd.debian.org/status/logs.php?arch=&pkg=rnp).

**Comment by antonsviridenko** [comment]
```
/<<PKGBUILDDIR>>/build/src/rnpkeys/rnpkeys --homedir /tmp/rnpctmpqo_3dshi/.rnp --edit-key --set-expire 10 primary_with_empty_password@rnp

sec   2048/RSA 14117ec7b8576dfb 2023-08-15 [SC] [EXPIRED 2023-08-15]
      369d4f087c5905904eddc4fc14117ec7b8576dfb
uid           primary_with_empty_password@rnp
FAIL
```
Is it possible that test takes more than 10 seconds to execute? Looks like that's the reason causing the failure.
This test seems to be already fixed in the master branch, now there are larger expiration periods there.

**Comment by dkg** [comment]
I've uploaded 0.17.0-3 to debian with this patch. i'll [check back on the build daemons](https://buildd.debian.org/status/logs.php?arch=&pkg=rnp) tomorrow and close this issue if 0.17.0-3 has built correctly on `mipsel` and `mips64el`.  Thanks, @antonsviridenko !

**Comment by dkg** [comment]
All good, it looks like that did the trick.  Thank you!

**Comment by ni4** [comment]
Thanks you guys!
