### ISSUE TITLE
Add Pipeline Test for Experimental Crypto Refresh / PQC Features

### ISSUE THREAD

**Issue by TJ-91** [rnpgp/rnp#2141]
I suggest to build and test the experimental features in the pipeline, that is, add a job that builds with `-DENABLE_CRYPTO_REFRESH=On -DENABLE_PQC=On` and execute `ctest`.

On the main branch (Commit aa11f73) building the experimental Crypto Refresh / PQC features fails due to a small mistake:

```
src/lib/pgp-key.cpp: In member function ‘bool pgp_key_material_t::get_grip(pgp_key_grip_t&) const’:
src/lib/pgp-key.cpp:3035:23: error: ‘key’ was not declared in this scope; did you mean ‘key_t’?
 3035 |             hash->add(key->ed25519.pub);
```

Without a pipeline test this goes unnoticed

**Comment by ni4** [comment]
Agree, we should definitely add some run with PQC, just didn't get to this task yet.
