### ISSUE TITLE
Query and set the features of keys

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#2178]
From RFC 4880 section 5.2.3.3 regarding features on self-signatures:

"It is good practice to verify that a self-signature imported into an implementation doesn't advertise features that the implementation doesn't support, rewriting the signature as appropriate."

As of today, it seems RNP doesn't offer support for checking the advertised features of a key, and also doesn't support changing them.

Because as of today Thunderbird doesn't support v5 keys, we face the issue that keys created with GnuPG 2.4.x advertise support for v5 keys (plus another feature) by default. If a user imports such a key into Thunderbird, and Thunderbird distributes that key, the advertised feature doesn't match the preference of the user's application.

Because GnuPG 2.4 is already widely deployed, I think it is a high priority to allow Thunderbird to fix those keys.

**Comment by kaie** [comment]
I have implemented a patch for RNP, and will submit a PR shortly.

**Comment by ni4** [comment]
Fixed via #2179.
