### ISSUE TITLE
CI: add runner with timestamp from the future.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#2183]
## Description

We should consider adding runners with future timestamp (~ 1 year, 5 years) to avoid issues like this one https://github.com/rnpgp/rnp/issues/1961
and be prepared for possible test artifact expiration/whatever else.

**Comment by ni4** [comment]
@maxirmx Would you like to take a look at this?

**Comment by maxirmx** [comment]
Ok, I will look at it.

**Comment by ni4** [comment]
Thanks!
