### ISSUE TITLE
Create v0.17.1 release with `rnp_signature_get_features`

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#2189]
## Description

Source: https://github.com/rnpgp/rnp/commit/74b70af135d0a1b05fe8ad63aac3f20319ebc4e8#commitcomment-138429079

From @kaie :
> Would the RNP team be willing to create a v0.17.1 release, based on the former v0.17.0 release, which adds this feature ([commit](https://github.com/rnpgp/rnp/commit/74b70af135d0a1b05fe8ad63aac3f20319ebc4e8#commitcomment-138429079))? This could allow those Linux distributions which ship RNP separately, to pick up this feature easily, and allow Thunderbird to make use of the new API in its current stable 115.x release.

**Comment by ni4** [comment]
@ronaldtse I think adding https://github.com/rnpgp/rnp/pull/2180 contents to release would be good idea?

**Comment by ronaldtse** [comment]
Agree with @ni4 . Thanks!

**Comment by ni4** [comment]
...also required to pick CI updates + Botan 3 support + OpenSSL 3.0 fixes (see https://github.com/rnpgp/rnp/pull/2190). @kaie don't you mind these changes? They should not have an impact for already existing behaviour and improve compatibility.

**Comment by kaie** [comment]
Hi @ni4 - If your intention is to include correctness fixes, plus compatibility fixes for a wider set of build environments and libraries, that makes sense to me. I'd suggest that you ask yourself: Would any long term support environment, that current contains Thunderbird 115.x, and is willing to take updated for it, but that also wants to minimize the amount of fixes it takes, be fine with your included changes? For example, stable Debian or RHEL? I'd exclude changes those stable environments might be unwilling to bring in.

**Comment by kaie** [comment]
CC @jfx2006

**Comment by ni4** [comment]
@kaie Yeah, this is mostly for systems which updated to Botan 3/latest OpenSSL 3.0 (like https://github.com/rnpgp/rnp/discussions/2159). For LTE nothing would change as they would continue to use older Botan/OpenSSL packages.

**Comment by kaie** [comment]
Hello, do you expect this to happen very soon, or are you blocked?

**Comment by ni4** [comment]
@kaie The only blocker was this thing : https://github.com/rnpgp/rnp/pull/2209 , however now it seems to be not of that importance as it is easily solvable by maintainers and mostly related to the v0.17.0.

**Comment by ni4** [comment]
Finally release is published: https://github.com/rnpgp/rnp/releases/tag/v0.17.1

**Comment by kaie** [comment]
Thank you. FYI, the release page also says function set_features was added, I assume that's a mistake.
