### ISSUE TITLE
Make sure rnp builds with the latest GoogleTest

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#2210]
## Description

See PR #2209 for more discussion.

**Comment by andreasstieger** [comment]
draft work also in #2212 I guess

**Comment by ni4** [comment]
@andreasstieger yeah, but now we should also make CI compatible with Botan 3.4.0, and latest Botan HEAD which renamed one module.

**Comment by andreasstieger** [comment]
#2212 was merged so this can be closed
