### ISSUE TITLE
Add GCM for v2 SEIPD?

### ISSUE THREAD

**Issue by falko-strenzke** [rnpgp/rnp#2218]
The crypto-refresh allows GCM as an AEAD mode for the v2 SEIPD packets. Is it desired to add GCM to RNP as well? In that case we might take on this task at some point.

@ni4 @TJ-91

**Comment by ni4** [comment]
I don't think this should be prioritized until it is needed in some way for PQC or get a lot of practical usage (which as I understand is zero now).

**Comment by falko-strenzke** [comment]
OK, then I think we can close it for now in order not to cloud up the issue list.
