### ISSUE TITLE
0.17.1 changelog claims rnp_key_set_features, but it is not present

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#2232]
```
$ git grep set_features v0.17.1
v0.17.1:CHANGELOG.md:* Added functions `rnp_key_set_features()` and `rnp_signature_get_features()`.
$ 
```

According to the changelog, `rnp_key_set_features` was added, but there is no other mention of `rnp_key_set_features` (or anything `set_features`, for that matter) in the source.  `rnp_signature_get_features`, by contrast, was indeed effectively introduced in 0.17.1.

**Comment by ni4** [comment]
Thanks for noticing this! Looks like typed this in while thinking on something other.
