### ISSUE TITLE
Missing 0.17.1 release

### ISSUE THREAD

**Issue by remicollet** [rnpgp/rnp#2235]
## Description

I noticed 0.17.1 was tagged, see https://github.com/rnpgp/rnp/releases/tag/v0.17.1
But nothing in release, see https://github.com/rnpgp/rnp/releases

So there is no asset attached to the version

Especially, the sources (.tar.gz) + signature (.asc)

**Comment by ni4** [comment]
@remicollet Yeah, we spent some time preparing the cleaned up source tarball ( PR #2228 ) and now new release is in a draft state. Should be published soon.

**Comment by ni4** [comment]
Here it goes: https://github.com/rnpgp/rnp/releases/tag/v0.17.1

**Comment by remicollet** [comment]
Thanks!
