### ISSUE TITLE
Missing destructor for rnp_op_verify_signature_t ?

### ISSUE THREAD

**Issue by csoler** [rnpgp/rnp#2257]
## Description

Most functions in RNP return opaque structures that need to be destroyed by the user using a *_destroy function. 
It seems however that rnp_op_verify_signature_t doesn't have a corresponding destructor (although it is a pointer).

Is that on purpose?

**Comment by ni4** [comment]
Thanks for noticing this! Yes, this is on purpose as handle would point to some internal structure (from the code: `*sig = &op->signatures_[idx];` ).
Made PR to update the documentation as well: https://github.com/rnpgp/rnp/pull/2258
