### ISSUE TITLE
Memory leaks fix

### ISSUE THREAD

**Issue by catap** [rnpgp/rnp#260]
When I worked on https://github.com/riboseinc/rnp/pull/259 I realised that we can't cleanup the code from memory leaks because some functions is too bigger and allocate/free resources made in different places.

So, I suggest to re-write the way how rnp works with memory, and move on to pool-based solution.

The idea is simple: we create a pool of memory and attach it to `rnp_ctx_t`, all parsers/etc are using special functions likes `rnp_malloc` or `rnp_alloc`, and never made `free`.

The pool released at one point `rnp_ctx_free` or `rnp_ctx_reset`.

@ronaldtse, @dewyatt, @ni4 what do you think?

**Comment by ni4** [comment]
Imho this can make life easier, anyway it would be good idea to make some wrapper functions rnp_alloc/rnp_free. But this should be minimalistic, to not overcomplicate the things :)

**Comment by catap** [comment]
Yes, the idea is make rnp allocator easy but use it everywhere to make life easier :)

**Comment by MohitKumarAgniotri** [comment]
I agree with the proposal considering the responsibility of allocating and freeing the memory is not very clear.

**Comment by dewyatt** [comment]
@catap I agree the memory leaks are very difficult to really eliminate, especially with regards to pgp_parse and friends.

We may also want to consider a reference counting mechanism, like json-c uses. Either way, there's definitely a lot of room for improvement.

**Comment by catap** [comment]
@dewyatt I feel that implementing reference counting mechanism is a much complicated than just a pool that release a memory than it doesn't need at all.

**Comment by dewyatt** [comment]
@catap That's very possibly true. Though it's also hard to define the point at which the pool is no longer needed, right?. For example, if the entire pool is freed in `rnp_end` that could be fine for some small CLI utility, but not so great for a long-running embedded application.

Anyways, I'm interested in seeing what you come up with.

**Comment by catap** [comment]
@dewyatt well... We can keep pool as depended on context, and reset or make free at `rnp_ctx_reset` and `rnp_ctx_free`.

So, for long-running embedded application that has a cycle it should create a new context or reset one of existed each cycle, and at end of cycle just free it or reset it if it supported reuse the context.

**Comment by dewyatt** [comment]
@catap I think maybe I see what you mean.

What do you think about a use-case like a high-performance web application that keeps some keys loaded that it uses on each request. Obviously it can't re-parse the keys on every request, it would likely be too slow. Would this be do-able with the above implementation?

I don't think we have to get everything perfect for every use-case on the first try anyways, but we should try to keep them in mind.

**Comment by catap** [comment]
@dewyatt good point. Let me take some time to thinking a while about it because I see one way but it looks like as workaround :)

**Comment by ronaldtse** [comment]
@dewyatt @catap I'd like to add the key loading case is a 110% practical issue that made GnuPG not work for us, exactly because of memory leakage.

**Comment by catap** [comment]
@ronaldtse, @dewyatt I have one idea.

Right now we have `rnp_t` and `rnp_ctx_t` and we can add pools to both of them.

A long-term to `rnp_t` that is using to keep information that will live during all application lives. For example loaded keys or something like this.

And a short-term to `rnp_ctx_t` that used as temporary pool that can use a function likes `rnp_encrypt_memory` or `rnp_decrypt_file` to allocate a temprorary memory for their needs, and this pool will reset/clean before and after any `rnp_*` public call.

This way helps us increase security and fix memory leaks :) 

What do you think?

**Comment by ni4** [comment]
In Objective C there is conception of 'autorelease' objects, which are safe to delete in event processing cycle, i.e. when after return from the code. We can reuse it - allocate temporary buffers/key copies/whatever else with 'autorelease' flag so it will be safe to delete them in pool_cleanup() call. And have one major cleanup call which will free everything in the pool, not only autorelease objects.

**Comment by catap** [comment]
@ni4 for C++ it will be `std:auto_ptr` that was 'fixed' as `std::unique_ptr`.

**Comment by ni4** [comment]
@ronaldtse @dewyatt Should we close this since right now we are checking for leaks via CI/will move to C++ sooner or later so don't have a need for any custom memory leaks handling code?

**Comment by ni4** [comment]
Closing this as obsolete.
