### ISSUE TITLE
Yum: define proper packages: rnp, librnp, and librnp-devel

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#30]
It is unnecessary to create separate packages for different executables such as `rnp`, `rnpv`. Let's bundle them together and only have 2 packages: executables and the development library.

UPDATE: As mentioned by @zgyarmati we shall have `rnp`, `librnp` and `librnp-devel` packages.

**Comment by zgyarmati** [comment]
I think it's better and more standard to have the following packages:
 'rnp' for the tools (rnp, rnpv, rnpkeys), depending on 'librnp'
'librnp' for the shared library
'librnp-devel' for the development files of the library

**Comment by ronaldtse** [comment]
Ah ha, wasn't as thorough as @zgyarmati . Agree!

**Comment by ronaldtse** [comment]
@ni4 @dewyatt can we close this? Thanks!

**Comment by dewyatt** [comment]
A bit late but I just checked and this can indeed be closed
