### ISSUE TITLE
GnuPG 2.3 extended private key format

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#371]
## Description

It looks like 2.3 is planning on adding yet another private key format ([keyformat.txt](http://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=agent/keyformat.txt;h=68fbdbc65aa4b06060c3b9036ccd39ada68e54e7;hb=HEAD))

With this in mind, I guess it's worth asking: Do we really want to support all the newer gpg private key formats?

This format doesn't look difficult to support, but tracking all the various changes in gpg for all the various formats could certainly become a headache.

Users can always export from gpg into the common denominator format that is actually standardized (PGP packets) with something like `gpg --export-secret-keys --armor`, and then import that into rnp.

Anyways, just putting this on the radar at least.

**Comment by catap** [comment]
@dewyatt I vote for implement it. I'm on G10 context at all and for me it looks like doesn't bigdeal to support this.

Anyway, I had this format inside my TODO list :)

**Comment by ronaldtse** [comment]
I'd vote to implementing it too. Thanks @catap. I'm so glad that we now have a key store interface. :-)

**Comment by maxirmx** [comment]
Closed via #1949
