### ISSUE TITLE
rnp --show-keys SIGSEGV

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#381]
## Description

There's all kinds of suspect things going on in `pgp_validate_key_sigs` and `pgp_validate_key_cb`.
I think there's a NULL `pgp_io_t` and some double frees going on at a minimum.

## Steps to Reproduce

1. `src/rnp/rnp --show-keys`

## Expected Behavior

I assume this is supposed to validate key signatures and show some output.

## Actual Behavior

segfault

**Comment by ni4** [comment]
Closing this since command --show-keys was removed in #912
