### ISSUE TITLE
gpg 2.1.15 complains about our KBX format

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#405]
## Description

This should be looked into at some point: https://github.com/riboseinc/rnp/pull/368#issuecomment-323347085

```
$ rm -rf ~/.rnp
$ src/rnpkeys/rnpkeys --gen-key --keystore-format=GPG21
$ docker run -ti --rm -v $HOME/.rnp:/root/.gnupg ubuntu:zesty gpg --list-keys
gpg: WARNING: unsafe ownership on homedir '/root/.gnupg'
gpg: parse_keyblock_image: more signatures than found in the meta data
gpg: keydb_get_keyblock failed: Invalid keyring
```

Newer gpg doesn't complain, but that may be because it's more lenient or something, so it should be more completely investigated.

**Comment by rrrooommmaaa** [comment]
Can I take this?

**Comment by ronaldtse** [comment]
Of course @rrrooommmaaa !
