### ISSUE TITLE
Crypto code cleanup

### ISSUE THREAD

**Issue by kriskwiatkowski** [rnpgp/rnp#491]
## Description

Currently we have a lot of boilerplate code in RNP. Let say we add new algorithm support to rnp. What one needs to do is to change many functions and modify switch-case blocks, possibly
forgetting about some places.

Each algorithm implements pretty much common set of functions. We could have have a macro with fixed number of arguments which would be used to register each algorithm and all helper functions which are mandatory. 
When rnp is called for any operation, first thing it would do  is to create some context which will carry structure with function pointers which correspond to algorithm being used (so for example, for
example if I do RSA verificaiton, I'll set pointers to RSA specific functions).

Then when 'frontend' functions (for example pgp_write_secret_mpis()) is called, it will use function pointer to do the operation, but it doesn't need to do know details of algorithm implementation.

What it gives us is:
- separation between frontend RNP functions and job done by low level impleemntation
- when developer adds new algorithm he knows from start that he needs to register all the functions with a macro - so he is forced to implement all required functions. But he won't need to know where to call them in RNP (as this will be a done by frontend code which will be common for all the algorithms). So code becomes less error prone
- we probably could remove copy-paste code from current code base

Others:
 * After #576 is done we can change all functions wrapping calls to botan so that they accept buffers instead of pointers to ``bignum_t``. It would be better if callers of crypto functions simply provide a buffer and crypto related operations take care of the rest

**Comment by ronaldtse** [comment]
@flowher make a lot of sense, looks like something we should get done soon 👍

**Comment by ni4** [comment]
Will not this add more complications then benefits? Say, for each asymmetric operations we have just 4 places where it is used: encryption, decryption, signing, verification. And places where key and MPIs are parsed in/out from the packet. 
Also all algorithms have different parameter sets so to make universal interface we'll need to have switch() with algorithm checking anyway, in all of these places.

And, actually, how often we'll add new asymmetric algorithms?

**Comment by flowher** [comment]
I think it won't. We have a lot of boiler plate code. For example ECDSA

```
> grep -r "ECDSA" * | grep "case" | wc -l
28
```

No we won't add algorithms (symmetric, asymmetric, hashes etc.) very often. 
Another argument is also - I think it will help to untangle many dependencies.

**Comment by dewyatt** [comment]
I think I kind of agree with both sides here.
On the one hand, it's clear that the current way we deal with this is messy, hard to maintain, and error-prone.
On the other hand, it does seem like a bunch of function pointers will add more complexity, acting as kind of hidden inputs.

I wonder if we could simplify things a bit with some lookup tables, like:
https://gist.github.com/dewyatt/88e661c22d5b0d5d90c36d1b3faacf07

At least it seems to me that could centralize *some* of the required info.

(I haven't had my coffee yet, so YMMV)

**Comment by ronaldtse** [comment]
I think @dewyatt 's solution would already solve this to a good extent.

**Comment by flowher** [comment]
It is an idea. Not sure it will help untangling dependencies. I'll probably think more about it when actually implementing it.

**Comment by ronaldtse** [comment]
Look forward to the work 👍

**Comment by ronaldtse** [comment]
@flowher any further thoughts on this issue?

**Comment by flowher** [comment]
No further ideas. It's waiting in TODO queue.

**Comment by ni4** [comment]
I would add that we should also change our crypto calls to use the standard approach everywhere - i.e., say, all 'sign' calls should have the same parameter types (uint8_t + len, or MPI), and the same  order (hash, then signature params, then key, for instance).

@dewyatt yeah, /crypto/ looks like a better place for symmetric.c

**Comment by flowher** [comment]
I was thinking about it. I would say it shouldn't. It should be cleaned up and then we may see where what goes. 
It will be indeed part of this implementation.

**Comment by ronaldtse** [comment]
I think we all agree that this file should get cleaned up, and most remaining code probably will end up in `/crypto/`.

**Comment by flowher** [comment]
To be implemented after AEAD support is added as those two features may clash

**Comment by ni4** [comment]
@ronaldtse @dewyatt Should we close this now? All crypto code was migrated to `/crypto/` some time ago.
