### ISSUE TITLE
Combine command line utils

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#69]
Currently we serve these binaries:

* `rnp` for "operations using keys", encrypting/decrypting, signing/verifying.
* `rnpv` for purely verifying
* `rnpkeys` for "operations on the keyset", such as key generation, key management

Pros:

* A user coming from `gpg` will expect one command to handle all functions. ( @randombit )
* Consolidates logic for option parsing etc ( @randombit )

Cons:

* They do perform independent functions, I think a preferable solution would be to aggregate shared functionality into a statically linked common library. ( @shaunwheelhouse )

I suggest:

* We combine `rnp` and `rnpv` into the same binary, and keep `rnpk` separate for key management.
* We create a statically linked common library for shared functionality between `rnp` and `rnpk`.

(this also relates to #2, #4)

**Comment by ni4** [comment]
@ronaldtse 
I'm starting to work on this. Do I think right that currently we stick to idea not to have rnpk/rnp but to squash all commands into the single utility, rnp?

**Comment by ni4** [comment]
@ronaldtse Could we close this now (ignoring my previous comment)? 
Now we have what is described in this issue - two commands, rnp/rnpkeys, and a library.

**Comment by ronaldtse** [comment]
Certainly @ni4 ! Sorry missed this message!
