### ISSUE TITLE
Rnpkeys : user is unable to create/append keys to custom keyring.

### ISSUE THREAD

**Issue by MohitKAgnihotri** [rnpgp/rnp#70]
The user is unable to create new keys in a custom user provided keyring. 
`usage: ./rnpkeys --generate-key --keyring=max`
expected output: new keyring with name "maxpub & maxsec" is created in the HOMEDIR.
Test case; `rnpkeys_generatekey_verifykeyRingOptions`

**Comment by MohitKumarAgniotri** [comment]
@ronaldtse, @shaunwheelhouse: Please help me defining the behaviour for option `--keyring`.
Many test case are failing for this item,

**Comment by ronaldtse** [comment]
I think @shaunwheelhouse is finishing off his branch for a consistent `homedir` and `keydir`, perhaps his branch will fix this issue?

**Comment by dewyatt** [comment]
Probably related: https://github.com/riboseinc/rnp/issues/21

**Comment by dewyatt** [comment]
I'm giving this a regression label since it looks like the `--keyring` option is completely unused now in the code base (though it's still accepted as a valid option, it appears to have no effect).

Given that GPG does support this option, we may want to consider supporting it again I guess.

**Comment by ni4** [comment]
Let's close this as not releveant anymore: we have `--homedir` and `--keyfile` options, which should be sufficient for all uses. If some edge case is not covered - we'd create a separate issue/PR.
