### ISSUE TITLE
Key material validation on key load

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#777]
## Description

Right now, once key is added to the keyring, it is validated, including signature(s) validation and key material validation.
However, key material validation is a bit time-consuming: with those checks rnp_tests run 14 minutes on my machine vs 6 minutes without checks.
So, the question is do we need to check each key's material during addition to the keyring?
Probably, smarter would be to check it only during key usage - i.e. for signing/encryption?

**Comment by hpk42** [comment]
On Fri, Nov 30, 2018 at 05:42 -0800, Nickolay Olshevsky wrote:
> ## Description
> 
> Right now, once key is added to the keyring, it is validated, including signature(s) validation and key material validation.
> However, key material validation is a bit time-consuming: with those checks rnp_tests run 14 minutes on my machine vs 6 minutes without checks.
> So, the question is do we need to check each key's material during addition to the keyring?
> Probably, smarter would be to check it only during key usage - i.e. for signing/encryption?

FWIW with deltachat and our current netpgp fork we found signing 
to be taking significant amounts of time. I prefer having potentially 
expensive checks only done once rather than on each signing.
the rnp test suite should not be the guide here (neither
should the deltachat-test suite) as they tend to generate
and re-generate new keys much more than in real-world use cases.

**Comment by ni4** [comment]
@hpk42 Thanks for the comment. Actually, idea is to do validation only once (and cache it), not each time signing is done. But, instead of doing it for each key (for, say, 100-key keyring), do it only for the keys which are used, and do it only once during the session. However more smart would be to move this functionality to the custom key storage, like this is done in GnuPG.

**Comment by hpk42** [comment]
On Wed, Dec 05, 2018 at 14:06 +0000, Nickolay Olshevsky wrote:
> @hpk42 Thanks for the comment. Actually, idea is to do validation only once (and cache it), not each time signing is done. But, instead of doing it for each key (for, say, 100-key keyring), do it only for the keys which are used, and do it only once during the session. However more smart would be to move this functionality to the custom key storage, like this is done in GnuPG.

If rnp allows to import a key in memory (optionally not validating it), 
returning a handle and then offers encrypt/decrypt/sign apis 
using those handles, and some methods to free the memory behind the handle,
that'd be useful. No need for caches or session state.

**Comment by ronaldtse** [comment]
Agree that we should have key validation separately performable without necessitating a cache.

And it would be great if key validation is done (and stored) at the key store to facilitate fast reuse!

**Comment by hpk42** [comment]
On Thu, Dec 06, 2018 at 17:06 -0800, Ronald Tse wrote:
> Agree that we should have key validation separately performable without necessitating a cache.
> 
> And it would be great if key validation is done (and stored) at the key store to facilitate fast reuse!

don't want to be annoying so i am going to note it once more ...
from a delta chat perspective key storage is not needed. 
We already store keys, including Autocrypt e-mail to key mappings,
and including private keys, in our own (sqlite) storage. 
What is needed is to be able to in-memory load and use them. 

do you have other use cases that make you want to 
tie things to keystores?

**Comment by ronaldtse** [comment]
@hpk42 we understand your use case, however other users of RNP often require a key storage. The point is we should make key validation available to use for users that don't require a key store, so your case is covered.

**Comment by ni4** [comment]
Key validation behaviour was changed as of RNP v0.16.0:
- all self-signatures are validated after loading key into memory (that's fast enough, however I filed #1797 as well)
- public key material is not validated 'mathematically', it is considerd to be protected via signatures validity
- secret key material is validated before the first key usage to avoid some sorts of attacks.

@ronaldtse @hpk42 Does this look good enough, so we may close this issue?

**Comment by hpk42** [comment]
i am not currently using rnp so better don't depend on me. thanks for the heads up!

**Comment by ronaldtse** [comment]
Thank you @ni4 ! This looks great, feel free to close this.
