### ISSUE TITLE
CHANGELOG in master branch

### ISSUE THREAD

**Issue by dewyatt** [rnpgp/rnp#818]
## Description

Right now we maintain a changelog (in markdown, so maybe another thing to convert) only in the `release/0.x` branch. It's difficult for users to find this and I'm thinking we would be better off with a different approach.

Since we only have a single release branch, it should be easy to keep a changelog in the master branch and just pull it into the release branches and modify as needed.

We could add to the changelog in master as we progress, like botan does in [news.rst](https://github.com/randombit/botan/blob/bb19424616f6ef9d382f9c31c465254626a7c714/news.rst#version-2100-not-yet-released).

**Comment by ronaldtse** [comment]
@dewyatt agree. Please help approach this as described. It's easy to convert Markdown (with `s/#/=/g` and `s/^  /*/g`).

**Comment by skalee** [comment]
It's even easier with Pandoc:

```
pandoc --atx-headers --from markdown --to asciidoc FILE.md > FILE.adoc
```

**Comment by dewyatt** [comment]
Yep I do love pandoc!

**Comment by ni4** [comment]
- closing this as changelog was added to the master via #1514
