### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#878]
## Description

When should we support Windows? Some organizations, like governmental ones, standardize on Windows. For example, if Metanorma integrates with RNP one day, it will need to run on Windows.

We could use AppVeyor (or Travis) as our Windows CI?

**Comment by kaie** [comment]
I've tried to build rnp for Windows. You're using a couple of things that aren't portable.

* the strsep function
* the __progname variable (you could use argv[0] instead)
* second parameter to function (probably should use a platform specific #ifdef)
* the command line utilities change the terminal settings (termios, no echo)
* GNU C regex

Could you use std::regex from C++11 instead?

**Comment by ronaldtse** [comment]
@kaie thank you for the attempt and the advice! Amazing this issue got a reply so quickly... :wink:

I believe we could use `std::regex` here, but this is really virgin territory for us so we're going to have a bit of a learning curve for Windows compatibility.

Thoughts @dewyatt @ni4 ?

**Comment by ni4** [comment]
@kaie Thanks for the input! Could you please clarify point #3 ("second parameter to function"), I'm not sure I get it.
@ronaldtse Those issues can be easily replaced with compatible code. However, while I have windows laptop around, I'll need some time to figure out correct toolchain usage to try to build the stuff. The last time I did such kind of task was around 15 years ago using the MinGW :-)

**Comment by kaie** [comment]
I also used cross compilation on Linux for my experiments. (I'm currently evaluating if the RNP library could be used in a cross-platform project.) I cross compiled libbotan, libjson-c, libbz2, libz. I haven't yet tried to build on Windows.

Regarding mkdir: On Linux, the function takes two parameters. The second is for file permissions. In the cross compile environment, it only takes a single parameter. I found a reference page on MSDN which says the posix version of the function (which takes two parameters) is deprecated on Windows.

**Comment by ni4** [comment]
@kaie Thanks for the detailed explanation.

**Comment by kaie** [comment]
I'll try to work on this for a bit. Just letting you know so we don't do duplicate work.

**Comment by kaie** [comment]
Please see the above pull request for library changes.

**Comment by ni4** [comment]
@ronaldtse @kaie Should we close this since we have CI for Windows via #993 ?

**Comment by ronaldtse** [comment]
Yes please, sorry @ni4 for missing this.
