### ISSUE TITLE
No installed header containing RNP_SUCCESS

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#897]
Using "make install", only the rnp.h header is installed.

That header mentions (in comments) the symbol RNP_SUCCESS, so you're encouraging applications to use that.

However, the exported header doesn't define it.

Is that intentional? Do you consider rnp_def.h a public head, and if yes, should it be installed by the "make install" target, too?

**Comment by dewyatt** [comment]
`rnp.h` should be the only header installed currently.

I'm thinking maybe we should:
1. Standardize on using `RNP_SUCCESS` in the docs. Currently some functions use `0 on success` and others use `RNP_SUCCESS`. API clients probably want more information than "success or failure", so we probably need to be exposing our error codes.
2. Extract the error codes enum from `rnp_def.h` into a new `error.h` or similar and install that additional header.

**Comment by joke325** [comment]
@dewyatt Could you please review the PR #968. There is a codecov check failure.
