### ISSUE TITLE
ssize_t isn't defined on Windows

### ISSUE THREAD

**Issue by kaie** [rnpgp/rnp#898]
The "signed size_t" type ssize_t is a POSIX type and is unavailable on Windows.

Although cross compilation worked, you're also using ssize_t in the public rnp.h header. You should change that to a portable size type.

**Comment by ronaldtse** [comment]
@ni4 would you have time to take care of this? Thanks!

**Comment by ni4** [comment]
@ronaldtse Sure.
The only question is that ssize_t is used in rnp_input_reader_t return type. Should I just change it to int?
cc @dewyatt

**Comment by dewyatt** [comment]
I think we have at least two options:
1. Change the `ssize_t` to an `int` and break the API+ABI. API clients like `ruby-rnp` could handle this with version checks, but other clients don't have ways of dealing with this that are as straightforward.
2. Deprecate `rnp_input_from_callback`, add a new `rnp_input_from_callback_ex` and an `rnp_input_reader_ex_t`. Disable compilation of the deprecated stuff on Windows.

**Comment by ronaldtse** [comment]
Frankly I'm fine with option 1, I don't think we have too much downstream usage yet.

**Comment by dewyatt** [comment]
Sounds good to me, let's try for option 1.

**Comment by mkmelin** [comment]
Any update on this? We run into this again now trying to get the libraries building with the Thunderbird build setup.

**Comment by ronaldtse** [comment]
@mkmelin thanks for raising this again. @ni4 @dewyatt any updates for option 1?

**Comment by ni4** [comment]
@ronaldtse @mkmelin Will switch to this task now.
