### ISSUE TITLE
Do we need redumper as a separate tool?

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#900]
## Description

We have packet dumper as a separate utility in src/apps/redumper (and a single one there).
Do we really need to have it as a separate tool?

I think it would be easier and more understandable for user to move all it's functions to `rnp --list-packets` command (which already duplicates some of the functionality).
And, possibly, add `dump.c` to `src/examples`.

**Comment by ronaldtse** [comment]
I'm fine either way, I think the motivation for having `redumper` separately was initially to aid the implementation of the FFI, and also mimic the functionality of `pgpdumper` (if I remembered the name right...), which is a simple tool that only performed one function well.

**Comment by ni4** [comment]
@ronaldtse Agree, let's leave it then. What about renaming to something more rnp-friendly? I.e. `rnpdump`, `rnpdumper`?

**Comment by ronaldtse** [comment]
@ni4 don't get me wrong, I'm fine either way 👍  If moving all its functions into `rnp --list-packets` is easier to maintain/use, let's do it. Thoughts @dewyatt ?

**Comment by ni4** [comment]
Looks like I misread your previous message. From my side the only complains are utility name, it's location in separate folder, and some code duplication.

**Comment by ronaldtse** [comment]
* utility name => agree with change
* list as example => i.e. as an FFI example. Agree.
* separate utility or not => ping @dewyatt ?

**Comment by dewyatt** [comment]
It's an interesting question. I'm tempted to say get rid of it personally.
We can provide the same functionality with `rnp --list-packets=pretty` or some kind of alternative formatting. We could do a symlink to rnp like `rnpdump` that would automatically do this, for example.

I admit I can sort of see the appeal of a small (maybe statically linked even) utility that does one thing well (a la `pgpdump`). I'm just not convinced it's worth it.

**Comment by ni4** [comment]
Then let's get rid of it as a separate utility and move to the examples folder. Will update #901 with these changes.

**Comment by ronaldtse** [comment]
Agreed guys!

**Comment by ronaldtse** [comment]
Since it's decided we'll close this! (will be implemented in #901)
