### ISSUE TITLE
Remove rnp --show-keys command.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#911]
## Description

This command existed since the netpgp and did a strange job - it did not display information about the keys but some basic information about the key signature expiration.
Since we have better functionality in `rnpkeys --list-keys/--list-sigs`, I think that duplicate one (which doesn't print any info now) may be removed.

**Comment by ni4** [comment]
@ronaldtse @dewyatt What do  you think?

**Comment by ni4** [comment]
@ronaldtse  ...including `--json` option for more structured output.

**Comment by ronaldtse** [comment]
@ni4 indeed!

**Comment by dewyatt** [comment]
Agreed
