### ISSUE TITLE
Trial tasks

### ISSUE THREAD

**Issue by ronaldtse** [rnpgp/rnp#937]
This issue is to pick or come up with some tickets within a 3-5 hour limit for trial tasks.

@dewyatt @ni4 could you help here? Thanks!

**Comment by ni4** [comment]
@ronaldtse I think checking some edge test cases would be good thing to start - no need to modify internals, but is a good dive into OpenPGP/rnp internals:
- #938 
- #939 
- #940 
- #941 
- #942

**Comment by ronaldtse** [comment]
Sorry for the delay. Here's the list of candidates.

Marko @msdev428
- C/C++, PGP, YubiHSM, PKCS-11

Tim @dfwdeveloper
- C++, Python, .Net, Windows/Unix/zOS

Peter @killy631
- C++/C, Crypto API, PKCS-11, OpenSSL, Windows/Linux/Mac/Solaris

Jan @joke325
- C/C++, Java, C#, Obj-C, Smart card, drivers, PKCS-11, Windows

Roman @rrrooommmaaa
- C++, NodeJS, Golang, .NET, Java, Windows/Linux/FreeBSD

Candidates:
1. Please look at previous PRs to know what you're expected of. Read the Contribution guide.
2. The work completed should be submitted as PRs to this repo.
3. We are happy to answer any question within the assigned issue.

@ni4 and @dewyatt could you help assign the trial tasks to the candidates? Thanks!

**Comment by ronaldtse** [comment]
(@dewyatt you wanted to add one or two Botan C++ tasks, feel free to add and assign)

**Comment by dewyatt** [comment]
Ref: https://github.com/rnpgp/rnp/issues/944

**Comment by ronaldtse** [comment]
@joke325 @rrrooommmaaa welcome! Please feel free to take on any further tasks here, and/or packaging tasks:

* https://github.com/rnpgp/chocolatey-rnp
* https://github.com/rnpgp/rnp-snap
* https://github.com/rnpgp/homebrew-rnp

**Comment by ronaldtse** [comment]
@antonsviridenko is our latest trial candidate, he's taking #941.

**Comment by rrrooommmaaa** [comment]
What permissions do I have for rnp-snap repository? Looks like I can't create a PR to empty repository.
Can you assign more tasks to me here too? Thanks you.

**Comment by ronaldtse** [comment]
@rrrooommmaaa you now have write access!

**Comment by ronaldtse** [comment]
This seems to be done for now, closing.
