### ISSUE TITLE
Check key packet length edge cases.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#938]
## Description

Make sure key packet can be correctly read with 1-byte, 2-byte and 4-byte packet lengths.
Also test negative cases - when key packet length is very large (say, 3Gb), zero, 2 bytes, etc.
Add separate test for these cases to rnp_tests suite, using the modified existing key file.
Key loading should be done via the FFI interface (see `rnp_import_keys()` function).

**Comment by ni4** [comment]
@msdev428 would you like to take this issue? Need your comment here to be able to assign it :) Thanks!

**Comment by msdev428** [comment]
@ni4 sure, I will check and let you know. Thanks!

**Comment by ni4** [comment]
@msdev428 great! Feel free to ask any questions here.

**Comment by msdev428** [comment]
@ni4 do I need to create PR from `master` branch?

**Comment by ni4** [comment]
@msdev428 no, please create a separate branch and then create PR from it. PR process in more details is described here: https://github.com/rnpgp/rnp/blob/master/docs/develop.adoc

**Comment by msdev428** [comment]
@ni4 sorry for delay.
Can you advise me to solve this issue?
To simulate key packet length, then do I need to replace key length field in pgp binary key file, right?

**Comment by ni4** [comment]
@msdev428 Yeah. Our implementation picks smallest possible packet header length. So you should cut existing header (see output of `rnp --list-packets keyfile`, prepend constructed header with different length field, and make sure key is loaded successfully.

**Comment by ni4** [comment]
@msdev428 you should be able to create a PR from your own fork, please see https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork for the details.

**Comment by msdev428** [comment]
@ni4 I created PR #950

**Comment by ni4** [comment]
@msdev428 Thanks, I'll review it and add comments to the PR.

**Comment by ni4** [comment]
Fixed in #1011
