### ISSUE TITLE
Ensure correct work with large packet sizes.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#940]
## Description

We need to check whether rnp correctly handles as large as possible packets.
This could be checked with zipped and signed 4Gb literal packet, built from single symbol, so it can be compressed to reasonable size to be added to tests suite.

Construct literal packet with largest possible size (4gb), using the 4-byte packet length, and compressed and then signed stream on top of it, and make sure it is processed well with rnp_op_verify() call.
Separate test file should be added to rnp_tests() suite.

**Comment by rrrooommmaaa** [comment]
Looks interesting to me

**Comment by dewyatt** [comment]
Let's go for it then!

**Comment by rrrooommmaaa** [comment]
Daniel. Is there a simple way to run only one test with `make test` command (or any other) from project root?

**Comment by dewyatt** [comment]
@rrrooommmaaa Yes, you can use ctest. For example, `ctest -R rnp_tests.test_stream_dearmor_edge_cases`. You can also list the tests with `ctest -N` (for the full list to show you would have to run make first).

**Comment by ni4** [comment]
@rrrooommmaaa once build you may run a single test with 'ctest -V -R rnp_tests.test_name'.

**Comment by rrrooommmaaa** [comment]
can I push to branch here (for subsequent PR) or do I need to fork?

**Comment by rrrooommmaaa** [comment]
also, did I understand correctly, that I you want 4G file to be placed in `test\data`?
I used ZIP compression and it's rather big -- 5.2M
Should I change compression algo or generate the file during the test?

**Comment by ni4** [comment]
@rrrooommmaaa Sorry for a late responce. I'll reply with more details in the PR you created.
