### ISSUE TITLE
Replace rnp_key_store_get_key_by_name() in tests and remove it.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#948]
## Description

Function `rnp_key_store_get_key_by_name()` was used in non-FFI CLI, and now is deprecated.
So it and all underlying code should be removed and replaced by other functions in tests.

**Comment by joke325** [comment]
@ni4 Could you please review the PR #957 (a replacement for PR #954).

**Comment by ni4** [comment]
@joke325 Done. Also there is no need to create new PR - you may rebase/squash to replace older code.
