### ISSUE TITLE
Numerous 'Hash finalization failed' message while running rnp_tests

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#955]
## Description

PR #946 introduced numerous error message output even on successfull tests run, which it didn't expose previously:
```
[pgp_hash_finish() /Users/nickolay/Ribose/rnp/src/lib/crypto/hash.cpp:274] Hash finalization failed
[pgp_hash_finish() /Users/nickolay/Ribose/rnp/src/lib/crypto/hash.cpp:274] Hash finalization failed
[pgp_hash_finish() /Users/nickolay/Ribose/rnp/src/lib/crypto/hash.cpp:274] Hash finalization failed
```

This is caused by incorrect handling of NULL `out` parameter, which is legitimate situation when you just want to cancel hashing and free allocated resources.

**Comment by ni4** [comment]
@joke325 Could you please take a look?

**Comment by joke325** [comment]
@ni4 My PR to fix this issue raised some codecov failures, could you please look at it?
