### ISSUE TITLE
rnpkeys: possible endless loop with endless output.

### ISSUE THREAD

**Issue by ni4** [rnpgp/rnp#969]
## Description

Using rnpkeys expert key generation mode with redirected input/output, and incorrect/empty stdin, may become endless producing endless output (just got 30Gb+ log file while running incorrectly configured tests).

Correct behavior would be to ask for input for few times and terminate, and to check whether stdin is opened at all.

**Comment by antonsviridenko** [comment]
Can be reproduced by running
`rnpkeys -g --expert`
and pressing `Ctrl+D` in a console.
