### ISSUE TITLE
clarify current release?

### ISSUE THREAD

**Issue by dkg** [rnpgp/rnp#972]
https://www.rnpgp.com/blog/ appears to indicate that 0.10.0 is the latest release.

The git tags in https://github.com/rnpgp/rnp contain v0.12.0 (that's the largest tagged version, with the exception of the tag `3.99.18`, which appears to predate v0.9.0 -- i don't understand what that is).  that tag is on branch `release/0.x`.

The git repo also contains commit 7d48330d03ff50cff345eafc0d19e97b9e9adbe5 (on branch `dewyatt-release-0.13.0`) which has a git commit message of `Release 0.13.0` from 2019-04-13. But there is no v0.13.0 tag.

Furthermore, the git repo's `master` branch apparently only follows/contains v0.9.0, and hasn't merged back in anything from the `release/0.x` branch.

Finally, none of the git tags appear to be signed with an OpenPGP signature.  This is a bit surprising for an OpenPGP project.

This is a pretty confusing situation for someone new to the project -- what version is the current release?  Where is development active?  Which branch should patches be submitted against?

**Comment by dewyatt** [comment]
The blog is out of date.
0.12.0 is the most recent release. Releases are always on a release/* branch.
0.13.0 was a work-in-progress release where I wanted to check on some things first but I've been overcome by other things for a while.

Ignore the 3.99.18 tag, I'm not sure who keeps pushing that one. 0.9.0 was the first actual version as I recall.

We have not established keys to use for signing commits yet.

`master` is where active development happens.

**Comment by dkg** [comment]
Thanks for the clarifications, @dewyatt!

Is there a reason not to merge the release/* branch back into master, to make it clear that master contains all the changes up to and including the current release?

I'd recommend removing the 3.99.18 tag and notifying everyone with commit access that they should also delete it from their local git repos.

**Comment by ronaldtse** [comment]
Thanks @dkg @dewyatt , agree on deleting the `3.99.18` tag to prevent confusion, and we probably should follow up on the rest of the raised issues...

**Comment by ni4** [comment]
Looks like 3.99.18 tag was my fault, got it from early era and didn't remove in time. Sorry.
Now it must be finally gone.

**Comment by dkg** [comment]
I can confirm that 3.99.18 is gone.  thanks for clearing up that piece
of the puzzle.

Any chance of an updated blog post?

Or releasing 0.13.0?

or merging the release branch back into master?  I experimented with
doing such a merge, but they have diverged pretty significantly, and i'm
not sure how to ensure that fixes that were applied to the release/0.x
branch have also been applied to master.

**Comment by dewyatt** [comment]
@dkg Apologies for the slow response.

> Or releasing 0.13.0?

I'll get this done soon because it's long overdue. I was holding off because I wanted to scrutinize one particular part of the FFI.

> or merging the release branch back into master? I experimented with doing such a merge, but they have diverged pretty significantly

See [here](https://github.com/rnpgp/rnp/blob/master/docs/develop/release-workflow.adoc) for an overview of our release workflow.

> i'm not sure how to ensure that fixes that were applied to the release/0.x branch have also been applied to master.

To see what commits are in `master` that are not in the release branch, you might do something like:
`git cherry -v origin/release/0.x origin/master`

**Comment by ni4** [comment]
@dkg version 0.13.0 was released few days ago.
Should we close this issue now?

**Comment by dkg** [comment]
On Sun 2020-01-05 02:41:28 -0800, Nickolay Olshevsky wrote:
> @dkg version 0.13.0 was released few days ago.
> Should we close this issue now?

How thorough is your release process?
https://www.rnpgp.com/software/rnp/docs/installation/ still contains
some references to 0.12.0.

https://www.rnpgp.com/software/rnp/docs/develop/packaging/ contains
references to 0.9.0.

It would be great to automate the library/tool release process in a way
that updates all public-facing documentation that refers to the most
recent version.

**Comment by dewyatt** [comment]
@dkg We haven't been releasing very often so it's something that could likely be improved. In fact, the release workflow docs are slightly out of date too IIRC.

**Comment by dkg** [comment]
just noting that 0.14.0 has apparently been released but [the blog](https://www.rnpgp.com/blog/) still claims 0.10.0 is the latest.

**Comment by ni4** [comment]
@dkg Thanks for noticing, we'll update the site.

**Comment by ni4** [comment]
@dkg Site was updated. Could we close this issue or you still have some questions?

**Comment by dkg** [comment]
thanks for updating the blog, and updating https://www.rnpgp.com/ as well.  i'm closing this.  if i have more questions about release timing/strategy/etc, i'll open other issues.
